### PR TITLE
Lspinheiro/chore/migrate azure executor autogen ext

### LINKED ISSUE #3645: Split azure code execution off from agnext
The azure code execution code brings in new (and pretty specific) dependencies. We should split it off from the main repo as an optional component.

### PR DESCRIPTION
**Pull request by lspinheiro**
## Why are these changes needed?

To remove code executor dependencies from the core package.

## Related issue number

Closes #3645 by removing `azure-core` from autogen-core dependencies and adding it to `autogen-ext`

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by jackgerrits** [comment]
@lspinheiro looks like there are some CI issues that need to be resolved before this can go in. Package structure and changes look good though.

**Comment by ekzhu** [comment]
Som uv lock issues.

**Comment by ekzhu** [comment]
Looks like a doc reference needs to be updated after the migration

**Comment by lspinheiro** [comment]
> Looks like a doc reference needs to be updated after the migration

@ekzhu  @jackgerrits , it should be fixed now. Thanks for the feedback and sorry for the time to fix.

**Pull request merged**
