### PR TITLE
Docker autogenstudio

### PR DESCRIPTION
**Pull request by r3d91ll**
I updated the Dockerfile.full, and Dockerfile.base with autostarts for AutogenStudio. I figured there would probably be a lot of attention on this project. Now that we have an excellent front end, we might as well make it a seamless setup.

## Why are these changes needed?

Easy setup for Autogen Studio

## Related issue number
#1172  #1241

## Checks

- [ X] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [X ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by qingyun-wu** [comment]
Why the file `start-docs-server.sh` is added to the website folder?

**Comment by qingyun-wu** [comment]
And I believe these two PRs should coordinate?  Both are trying to add docker for autogenstudio. @victordibia @gagb

**Comment by r3d91ll** [comment]
> @r3d91ll before I review your PR what do you think about: #1286

I'm in full support of it. I didn't have the time to track down why the Dockerfile.dev had a package conflict. Your solution is elegant as it solves the local build issue I saw as well as the codespaces issue you found. We just need to make sure that users know to look in the .devcontainers. I'm willing to draft this for now or close in lieu of your pull.

**Comment by gagb** [comment]
> > @r3d91ll before I review your PR what do you think about: #1286
> 
> I'm in full support of it. I didn't have the time to track down why the Dockerfile.dev had a package conflict. Your solution is elegant as it solves the local build issue I saw as well as the codespaces issue you found. We just need to make sure that users know to look in the .devcontainers. I'm willing to draft this for now or close in lieu of your pull.

Thank you for the kind words! Would you like to draft it and I can very quickly review it?

**Comment by r3d91ll** [comment]
> > > @r3d91ll before I review your PR what do you think about: #1286
> > 
> > 
> > I'm in full support of it. I didn't have the time to track down why the Dockerfile.dev had a package conflict. Your solution is elegant as it solves the local build issue I saw as well as the codespaces issue you found. We just need to make sure that users know to look in the .devcontainers. I'm willing to draft this for now or close in lieu of your pull.
> 
> Thank you for the kind words! Would you like to draft it and I can very quickly review it?

Thank you for the consideration, but unfortunately, I will not have the time to give this the attention it deserves until early next week. Given the critical nature of ensuring a smooth development process and the importance of avoiding the pitfalls associated with developing as root – a topic I'm quite passionate about, as evidenced by my recent pull request (#1251) – it might be more pragmatic for you to take the lead on this.

If you're able to address it before Sunday, I will certainly make time to review it then. Otherwise, I plan to tackle it early next week. Our collective focus on providing clear guidance and maintaining best practices for our developers is paramount, especially in the context of developing as root and the risks that poses to our community.

Best regards

**Comment by gagb** [comment]
> > > > @r3d91ll before I review your PR what do you think about: #1286
> > > 
> > > 
> > > I'm in full support of it. I didn't have the time to track down why the Dockerfile.dev had a package conflict. Your solution is elegant as it solves the local build issue I saw as well as the codespaces issue you found. We just need to make sure that users know to look in the .devcontainers. I'm willing to draft this for now or close in lieu of your pull.
> > 
> > 
> > Thank you for the kind words! Would you like to draft it and I can very quickly review it?
> 
> Thank you for the consideration, but unfortunately, I will not have the time to give this the attention it deserves until early next week. Given the critical nature of ensuring a smooth development process and the importance of avoiding the pitfalls associated with developing as root – a topic I'm quite passionate about, as evidenced by my recent pull request (#1251) – it might be more pragmatic for you to take the lead on this.
> 
> If you're able to address it before Sunday, I will certainly make time to review it then. Otherwise, I plan to tackle it early next week. Our collective focus on providing clear guidance and maintaining best practices for our developers is paramount, especially in the context of developing as root and the risks that poses to our community.
> 
> Best regards

I agree with the importance of this @r3d91ll! I will submit a PR tomorrow morning and add you as a reviewer :)

**Comment by gagb** [comment]
> > > > > @r3d91ll before I review your PR what do you think about: #1286
> > > > 
> > > > 
> > > > I'm in full support of it. I didn't have the time to track down why the Dockerfile.dev had a package conflict. Your solution is elegant as it solves the local build issue I saw as well as the codespaces issue you found. We just need to make sure that users know to look in the .devcontainers. I'm willing to draft this for now or close in lieu of your pull.
> > > 
> > > 
> > > Thank you for the kind words! Would you like to draft it and I can very quickly review it?
> > 
> > 
> > Thank you for the consideration, but unfortunately, I will not have the time to give this the attention it deserves until early next week. Given the critical nature of ensuring a smooth development process and the importance of avoiding the pitfalls associated with developing as root – a topic I'm quite passionate about, as evidenced by my recent pull request (#1251) – it might be more pragmatic for you to take the lead on this.
> > If you're able to address it before Sunday, I will certainly make time to review it then. Otherwise, I plan to tackle it early next week. Our collective focus on providing clear guidance and maintaining best practices for our developers is paramount, especially in the context of developing as root and the risks that poses to our community.
> > Best regards
> 
> I agree with the importance of this @r3d91ll! I will submit a PR tomorrow morning and add you as a reviewer :)

@r3d91ll here is the PR https://github.com/microsoft/autogen/pull/1333

**Comment by r3d91ll** [comment]
> > > @r3d91ll before I review your PR what do you think about: #1286
> > 
> > 
> > I'm in full support of it. I didn't have the time to track down why the Dockerfile.dev had a package conflict. Your solution is elegant as it solves the local build issue I saw as well as the codespaces issue you found. We just need to make sure that users know to look in the .devcontainers. I'm willing to draft this for now or close in lieu of your pull.
> 
> Thank you for the kind words! Would you like to draft it and I can very quickly review it?

Thank you for the consideration, but unfortunately, I will not have the time to give this the attention it deserves until early sometime next week. It might be more pragmatic for you to take the lead on this. My day job is pretty all-consuming at the moment and I can only spare time on my weekends.

If you can address it before Monday, I will certainly make time to review it then. Otherwise, I plan to tackle it sometime Monday or Tuesday at the earliest. 

Best regards

**Comment by gagb** [comment]
@r3d91ll the other PR was merged, please feel free to suggest changes per your this PR: https://github.com/microsoft/autogen/pull/1333

**Comment by KierenB** [comment]
FWIW I think that this PR could be improved by adding something about data/config persistence. As it stands any customisation a new user does will be lost when the container restarts. Maybe add something around volume mappings? Otherwise this is awesome and it does "just work" - nice work @r3d91ll

**Comment by sonichi** [comment]
@gagb @victordibia checking in here.

**Comment by gagb** [comment]
> > @r3d91ll before I review your PR what do you think about: #1286
> 
> I'm in full support of it. I didn't have the time to track down why the Dockerfile.dev had a package conflict. Your solution is elegant as it solves the local build issue I saw as well as the codespaces issue you found. We just need to make sure that users know to look in the .devcontainers. I'm willing to draft this for now or close in lieu of your pull.

@r3d91ll the new dev containers were merged some time ago. If you'd like to include changes of this PR, let us know or better make a new PR.

**Comment by gagb** [comment]
@r3d91ll I am closing this PR. Please re-open if you need these changes.

**Pull request closed without merging**
