### PR TITLE
Add gpt-4o-mini to model list

### PR DESCRIPTION
**Pull request by umermansoor**
## Why are these changes needed?

This adds support for gpt-4o-mini that was released today by OpenAI. https://platform.openai.com/docs/models/gpt-4o-mini

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by umermansoor** [comment]
@microsoft-github-policy-service agree

**Comment by qingyun-wu** [comment]
Thanks @umermansoor for the contribution! Could you please fix the code format problems by running [pre-commit](https://microsoft.github.io/autogen/docs/contributor-guide/pre-commit)? Thanks!

**Comment by umermansoor** [comment]
@qingyun-wu Thanks for flagging this. I have fixed the formatting issue and verified it by running pre-commit. (There was a formatting issue in `test/agentchat/test_conversable_agent.py`)

```
autogen@89249a1a81e6:/workspaces/autogen$ pre-commit run --show-diff-on-failure --color=always --all-files
check for added large files..............................................Passed
check python ast.........................................................Passed
check yaml...............................................................Passed
check toml...............................................................Passed
check json...............................................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
check for merge conflicts................................................Passed
detect private key.......................................................Passed
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
don't commit to branch...................................................Passed
black....................................................................Passed
ruff.....................................................................Passed
codespell................................................................Passed
mypy.....................................................................Passed
- hook id: mypy
- duration: 3.36s

Success: no issues found in 34 source files

nbqa-black...............................................................Passed
```

**Comment by umermansoor** [comment]
Hi @qingyun-wu @LittleLittleCloud I updated the code to remove formatting issue. Can you pls review this?

**Comment by Hk669** [comment]
> Hi @qingyun-wu @LittleLittleCloud I updated the code to remove formatting issue. Can you pls review this?

i dont think it resolved, can you run the `pre-commit` again. looks good to me otherwise. thanks for the PR.

**Comment by umermansoor** [comment]
Hi @Hk669 Thank you for checking. I'm not sure what happened as I had verified that pre-commit checks were passing before I pushed my changes. 

I just ran it again and it added a new line character and I have verified again that pre-commit is passing (my output below)

Could you pls run this again? Thank you

```
autogen@89249a1a81e6:/workspaces/autogen$ pre-commit run --all-files
check for added large files..............................................Passed
check python ast.........................................................Passed
check yaml...............................................................Passed
check toml...............................................................Passed
check json...............................................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
check for merge conflicts................................................Passed
detect private key.......................................................Passed
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
don't commit to branch...................................................Passed
black....................................................................Passed
ruff.....................................................................Passed
codespell................................................................Passed
mypy.....................................................................Passed
- hook id: mypy
- duration: 28.29s

Success: no issues found in 34 source files

nbqa-black...............................................................Passed
```

**Review by Hk669 — APPROVED** [review]
looks good to me. thanks for the PR @umermansoor

**Comment by umermansoor** [comment]
@Hk669 Awesome. I updated the branch with latest changes

**Review by IANTHEREAL — APPROVED** [review]

**Comment by umermansoor** [comment]
@sonichi Can you pls review and merge this MR? It's been open for a while. I merged latest main and GitGuardian is failing because of a code example (no secret) that was merged into main. If you haven't already, I can fix that in a separate MR later today.

**Comment by melvinmt** [comment]
can we also add support for `gpt-4o-2024-08-06`?

**Comment by umermansoor** [comment]
Thanks. Added it here: https://github.com/microsoft/autogen/pull/3329

**Pull request merged**
