### PR TITLE
Feature/autogenstudio UI extra headers

### PR DESCRIPTION
**Pull request by ronaldpereira**
## Why are these changes needed?

**Problem:** The autogenstudio library lacked the ability to specify default headers for API requests. This caused issues when APIs required specific headers to be included in every request.

**Solution:** I've extended autogenstudio to accept an optional default_headers parameter. This parameter allows developers to define a dictionary containing the desired headers, which will be automatically included in all API requests generated by autogenstudio.

For example, when any custom API needed some extra headers to complete the request:
`"default_headers": {"X-Requester-Token": "<requester_token>"}`
The llm_config parameter already accepts this configuration, but it wasn't possible to pass it via the autogenstudio via model creation.

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

## Extra info

This MR was done originally in [here](https://github.com/microsoft/autogen/pull/2334), but it was needed to create this in the upstream repo for openai tests to run.

### CODE REVIEW

**Comment by victordibia** [comment]
@ronaldpereira ,
Thanks, this looks like a valuable PR enabling the ability to add default_headers.
Two things:
-   it seems that you have made changes to `client.py`. I would separate that into a separate PR to effectively discuss that change since it is beyond the scope of autogenstudio 
- we are finalizing a PR that improves the database for autogenstudio which will likely conflict with the changes you have made here to `datamodel.py` and `dbutils.py`. I'd love to work with you to integrate `default_headers` in that PR. https://github.com/microsoft/autogen/pull/2425

**Comment by ronaldpereira** [comment]
Thanks for the review, @victordibia !

> it seems that you have made changes to `client.py`. I would separate that into a separate PR to effectively discuss that change since it is beyond the scope of autogenstudio

Hmm, I usually don't like to split a single MR feature into two different MRs because it can result to code being broken. I like to view this MR as a frontend+backend unity, as if I merge the frontend first, it can break the model creation in studio unwillingly.

> we are finalizing a PR that improves the database for autogenstudio which will likely conflict with the changes you have made here to `datamodel.py` and `dbutils.py`. I'd like to work with you to integrate `default_headers` in that PR. [Rewrite AutoGen Studio Database Layer to Use SQLModel ORM #2425](https://github.com/microsoft/autogen/pull/2425)

I thinking of a better approach to this: I can point this MR to your MR and keep updating and solving merge conflicts that will eventually show. Then when your MR is in the ready state, we can merge this MR into it and then merge all of them into the main branch. Do you think it's a better idea?

I can still split this into two different MRs and create a merge dependency for the backend in the frontend part if you wish, no problem.

**Comment by rysweet** [comment]
This PR is against AutoGen 0.2. AutoGen 0.2 has been moved to the 0.2 branch. Please rebase your PR on the 0.2 branch or update it to work with the new AutoGen 0.4 that is now in main.

**Comment by rysweet** [comment]
Hi @ronaldpereira - we rebased this for you but it looks like there are still some conflicts. If you are still interested in bringing this forward please have a look at resolving the conflicts and greening the CI

**Comment by ronaldpereira** [comment]
Hello @rysweet,

The recent changes to the autogen studio have affected the database and UI design I've implemented, so adjustments will be needed to make this mergeable. I believe it would be more efficient to create a new branch from scratch using the current codebase, rather than trying to adapt the existing one in this MR.

Therefore, I'll close this MR for now and will open a new one, referencing this, once the new branch is ready.

Thank you for rebasing this MR for me.

**Pull request closed without merging**
