### PR TITLE
teachable_agent working functions

### PR DESCRIPTION
**Pull request by jrknox1977**
## Why are these changes needed?
I needed teachableAgent work with functions. So I modified it. :-) 

I examined the other agents to see why they could handle functions but teachableAgent coud not. I then modified teaachableAgent to include code for functions. 

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by jrknox1977** [comment]
@microsoft-github-policy-service agree

**Comment by jrknox1977** [comment]
@rickyloynd-microsoft I added the ability for teachable_agent to be used in conversations with functions.

**Comment by rickyloynd-microsoft** [comment]
Thank you @jrknox1977 for the contribution! Can you add a short file autogen/test/agentchat/test_teachable_agent_functions.py to test the new functionality? You can use autogen/test/agentchat/test_teachable_agent.py as a general pattern.

**Comment by gagb** [comment]
@jrknox1977 are you able to make the changes @rickyloynd-microsoft suggested?

**Pull request closed without merging**
