### PR TITLE
General Enhancements in agentchat 2.0

### PR DESCRIPTION
**Pull request by WaelKarkoub**
## Why are these changes needed?

I noticed some inconsistencies in the formatting of the files, error handling, and type hints. I've only cleaned up the mistakes that I found were "obvious."

Moved this branch from my fork to the main repo, closing https://github.com/microsoft/autogen/pull/1729

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by sonichi** [comment]
@WaelKarkoub the test failed.

**Comment by jackgerrits** [comment]
To fix I think you need to update graph_utils.py to fix a circular import. A relative import might fix it

**Comment by WaelKarkoub** [comment]
@jackgerrits thanks! Not sure how my tests passed locally

**Comment by WaelKarkoub** [comment]
@sonichi tests are looking good now

**Comment by ekzhu** [comment]
The open AI test failed due to flaky test. This test is being removed in #1835

**Review by ekzhu — APPROVED** [review]

**Comment by sonichi** [comment]
> The open AI test failed due to flaky test. This test is being removed in #1835

Two caching tests fail: https://github.com/microsoft/autogen/actions/runs/8203756633/job/22437056654?pr=1906
Is #1835 fixing those?

**Comment by ekzhu** [comment]
@WaelKarkoub I know it's not part of this PR... but the cache test fails due to the working directory is not wiped between each run of agent conversations.

This: https://github.com/microsoft/autogen/blob/main/test/agentchat/test_cache_agent.py#L110
and this: https://github.com/microsoft/autogen/blob/main/test/agentchat/test_cache_agent.py#L154

in both cases you can use temporary directory context manager to make sure the work_dir of the code executor is wiped.

**Comment by WaelKarkoub** [comment]
@ekzhu added temp directories for those functions; I tested them locally and they worked as expected. Looking though the [docs](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory), we could see [PermissionError](https://docs.python.org/3/library/exceptions.html#PermissionError), just a heads up

**Pull request merged**
