### PR TITLE
Added example .txt file for agentchat_langchain sample notebook

### PR DESCRIPTION
**Pull request by jasondotparse**
## Why are these changes needed?

While running the agentchat_langchain example notebook, I encountered an error in the cell that attempts to use `langchain.tools.file_management.ReadFileTool` to read a file called `Test.txt`... that file does not exist in the directory, so I added it in order to make sure that future readers don't encounter that error and get confused. 

Also added a helper function to the notebook which gets the correct file path. 

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by jasondotparse** [comment]
> @jasondotparse please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by sonichi** [comment]
Is the same issue noted in #265 ?

**Review by gagb — APPROVED** [review]
Thank you for the PR!

**Review by sonichi — COMMENTED** [review]
There is a minor formatting error: https://github.com/microsoft/autogen/actions/runs/6667771927/job/18121879951?pr=373
Could you please fix that? Then we can merge.

**Comment by sonichi** [comment]
> There is a minor formatting error: https://github.com/microsoft/autogen/actions/runs/6667771927/job/18121879951?pr=373 Could you please fix that? Then we can merge.

@jasondotparse this should be an easy fix. Does adding a new line in the end of test.txt break anything in the notebook?

**Comment by jasondotparse** [comment]
Hey there, sorry for the slow reply, I've just got back from vacation. Will make the quick update tomorrow when I get back to my desk 👍

**Comment by jasondotparse** [comment]
> > There is a minor formatting error: https://github.com/microsoft/autogen/actions/runs/6667771927/job/18121879951?pr=373 Could you please fix that? Then we can merge.
> 
> @jasondotparse this should be an easy fix. Does adding a new line in the end of test.txt break anything in the notebook?

Nope, doesn't break anything in the notebook. Updated.

**Pull request merged**
