### PR TITLE
Adding Benchmarks to agbench

### PR DESCRIPTION
**Pull request by husseinmozannar**
## Why are these changes needed?

Adding benchmarks back into autogen. Namely GAIA, Assistantebench, WebArena and HumanEval.

PR is a draft while we figure out licenses.

## Related issue number

Related PR #3711 - was part of that but moved to separate PR to not block agbench
## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by husseinmozannar** [comment]
@afourney added license files to benchmarks

**Comment by afourney** [comment]
Can we move the licenses into the folder where we are using code? So eval_utils, and common? We should also get sign-off from folks who know better how this is usually done. To be clear, these license don't apply to most of the code... only the small eval scripts.

**Comment by husseinmozannar** [comment]
> Can we move the licenses into the folder where we are using code? So eval_utils, and common? We should also get sign-off from folks who know better how this is usually done. To be clear, these license don't apply to most of the code... only the small eval scripts.

Done!

**Review by afourney — APPROVED** [review]
Thanks! Looks good.

**Pull request merged**
