### PR TITLE
update return type of WolframAlphaAPIWrapper.run()

### PR DESCRIPTION
**Pull request by 1073710317**
## Why are these changes needed?
fix the wrong return type of WolframAlphaAPIWrapper.run()

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by afourney — APPROVED** [review]
Looks good to me.

**Review by sonichi — APPROVED** [review]

**Comment by sonichi** [comment]
Please fix the test error: https://github.com/microsoft/autogen/actions/runs/6737212619/job/18314177230?pr=523

**Comment by 1073710317** [comment]
> Please fix the test error: https://github.com/microsoft/autogen/actions/runs/6737212619/job/18314177230?pr=523

image

Thank you for pointing out this problem, It is a version compatibility problem, I will solve this problem as soon as possible.

**Comment by 1073710317** [comment]
> Please fix the test error: https://github.com/microsoft/autogen/actions/runs/6737212619/job/18314177230?pr=523

I have fixed the test error, Please try it again, Thanks! @sonichi

**Review by kevin666aa — APPROVED** [review]

**Pull request merged**
