### PR TITLE
Update Dockerfile python version

### PR DESCRIPTION
**Pull request by Jollerprutt**
## Why are these changes needed?

python 3.11 required

### CODE REVIEW

**Comment by gagb** [comment]
@Jollerprutt the readme says Studio supports 3.10+: https://github.com/microsoft/autogen/tree/main/samples/apps/autogen-studio

**Comment by Jollerprutt** [comment]
Yes the messages are a bit mixed.
In the readme it says 3.10+.
https://autogen-studio.com/autogen-studio-ui
Here it says 3.11 specifically.
"AutoGen Studio UI 2.0 operates on Python 3.11. It’s crucial to have this version installed to avoid any compatibility issues."

With a fresh container using 3.10 the UI wouldn't load, switching to 3.11 everything was fine.

**Comment by gagb** [comment]
@Jollerprutt can share the error message when you use 3.10? Also which image were you using?

**Comment by jackgerrits** [comment]
Looks like this is dormant, if you want to pick this up again please feel free to reopen. Thanks!

**Pull request closed without merging**
