### PR TITLE
Support openai assistant v2 API

### PR DESCRIPTION
**Pull request by IANTHEREAL**
## Why are these changes needed?

This PR introduces support for the newly released OpenAI Assistant API v2, incorporating significant changes outlined in the [migration guide](https://platform.openai.com/docs/assistants/migration). We aim to ensure compatibility with the existing API v1 without disrupting current implementations. The key modifications include:

1. Dual API Support: Refactored the assistant creation and update functions to support both API v1 and v2 seamlessly.
2. Enhanced File Handling: When a user calls the GPT assistant agent with file_ids, the code now attempts to create a vector store and utilizes file_search. This enhancement maintains compatibility with the existing user codebase.
3. Updated Testing Suite: Expanded the test suite to verify functionality against the API v2 specifications while preserving a subset of tests for API v1 to ensure ongoing compatibility.

By making these changes, it aim to leverage the advancements in API v2 while maintaining a smooth transition for existing applications still utilizing API v1.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by ekzhu — APPROVED** [review]
We also need a user guide page in `website/docs/topics/` to document the OAI Assistant.

**Comment by ekzhu** [comment]
Can you recreate a new PR from the Microsoft repo so we can run the openai tests?

**Comment by IANTHEREAL** [comment]
@ekzhu I created a new PR.  And can I add the docs under `website/docs/topics/` later ?

**Comment by ekzhu** [comment]
Close this for work continued in #2466

**Pull request closed without merging**
