### PR TITLE
Added functionality to pass environment variables to code execution

### PR DESCRIPTION
**Pull request by abhishek-ravikumar-kulkarni**
Added a way to inject env variables into during the docker code execution phase

## Why are these changes needed?

There was no way of passing the env configs to docker env in realtime, and it would have been easier if it was one of the options when we use define code_execution_config

## Related issue number

Had raised this issue in - https://github.com/microsoft/autogen/issues/585

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by abhishek-ravikumar-kulkarni** [comment]
@microsoft-github-policy-service agree [company="{Freshworks}"]

**Comment by abhishek-ravikumar-kulkarni** [comment]
@[microsoft-github-policy-service](https://github.com/apps/microsoft-github-policy-service) agree company="Freshworks"

**Comment by abhishek-ravikumar-kulkarni** [comment]
@[microsoft-github-policy-service](https://github.com/apps/microsoft-github-policy-service) agree

**Comment by afourney** [comment]
This appears to only work when using Docker. Ideally, we would also allow the environment variables to be set when running natively.

**Comment by abhishek-ravikumar-kulkarni** [comment]
Alright, will raise pr with the changes for the same.

**Comment by threatlevelmidnight10** [comment]
@afourney i believe for native executions it's best for developers to set their own environment variables.

**Pull request closed without merging**
