### PR TITLE
Update more notebooks to be available on the website

### PR DESCRIPTION
**Pull request by jackgerrits**
## Why are these changes needed?

Adds the following to the website:
 - agentchat_capability_long_context_handling.ipynb
 - agentchat_chess.ipynb
 - agentchat_compression.ipynb
 - agentchat_custom_model.ipynb
 - agentchat_groupchat_research.ipynb
 - agentchat_teachability.ipynb
 - agentchat_teaching.ipynb

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by qingyun-wu** [comment]
Looks good! Could you help make this notebook work as well? https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_customized.ipynb
Thank you!

**Comment by rickyloynd-microsoft** [comment]
The new requirements section of agentchat_teachability.ipynb now looks like this:

image

Is that the expected formatting?

**Comment by jackgerrits** [comment]
Yes, that is expected. That renders as an admonition on the website

**Review by rickyloynd-microsoft — APPROVED** [review]
Looks great!

**Comment by sonichi** [comment]
Could you resolve the conflict?

**Comment by jackgerrits** [comment]
@sonichi resolved

**Comment by sonichi** [comment]
I see 
image

**Comment by jackgerrits** [comment]
okay that one is resolved now too

**Pull request merged**
