### PR TITLE
Add token usage termination

### LINKED ISSUE #4022: Termination condition for token/cost budget
### What feature would you like to be added?

Add a termination condition to stop a task execution from using too many tokens. 

Depends on https://github.com/microsoft/autogen/issues/4017

### Why is this needed?

Important to save money.

### PR DESCRIPTION
**Pull request by ekzhu**
Resolve #4022

Requires #4028 to merge first

### CODE REVIEW

**Review by victordibia — COMMENTED** [review]
Looking good.
Any thoughts on timeout/time based termination?

**Comment by ekzhu** [comment]
> Looking good. Any thoughts on timeout/time based termination?

Good idea, let's have one

**Review by ekzhu — COMMENTED** [review]
Fixed all tests.

**Review by victordibia — APPROVED** [review]
Looks good! Thanks for the fast turn around on this!

**Pull request merged**
