### PR TITLE
Add OpenAI Gemini Example for VertexAI Notebook

### PR DESCRIPTION
**Pull request by luxzoli**
## Why are these changes needed?

* Add example of how to use Gemini with Autogen using the OpenAI client
* Correct authentication commands with `gcloud` for environments outside of Google Cloud Shell

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by olaoluwasalami** [comment]
@luxzoli The docs/check(pull_request) is failing, Please can you check this?

**Comment by olaoluwasalami** [comment]
@luxzoli for the Service Account, instead of the basic role(editor role), can we look at changing it to predefined roles? We can work on this together

**Comment by luxzoli** [comment]
> @luxzoli for the Service Account, instead of the basic role(editor role), can we look at changing it to predefined roles? We can work on this together

Good point, and thanks a lot for the support! The [roles/aiplatform.user](https://cloud.google.com/vertex-ai/docs/general/access-control) should actually have all the rights which we need for VertexAI. Of course, for things like impersonation additional permissons are needed, but I guess that is out of scope here

**Comment by luxzoli** [comment]
> @luxzoli The docs/check(pull_request) is failing, Please can you check this?

This should be fixed now :)

**Comment by luxzoli** [comment]
> @luxzoli for the Service Account, instead of the basic role(editor role), can we look at changing it to predefined roles? We can work on this together

Now the [Vertex AI User](https://cloud.google.com/vertex-ai/docs/general/access-control#aiplatform.user) role is used instead

**Review by olaoluwasalami — APPROVED** [review]

**Pull request merged**
