### PR TITLE
Transform to add an agent's name into the message content

### PR DESCRIPTION
**Pull request by marklysze**
The recent addition of non-OpenAI client classes has expanded the utility of AutoGen to a lot of different models through other cloud providers as well as the ability to run it with local LLMs.

However, the `name` field on each message is removed as only OpenAI can accept and utilise that field.

This means that functionality, like the GroupChat's select speaker, isn't as effective as the LLM may not be able to determine which 'agent' belongs to each message.

This PR introduces a transform that can add an agent's name to the start or end of message's text content. As this is a transform, it isn't permanent and doesn't change the original message.

How it works:
```
from autogen.agentchat.contrib.capabilities import transform_messages, transforms

# Create a transform
name_transform = TextMessageContentName(position="start", format_string="'{name}' said:\n")

# Create the TransformMessages
context_handling = transform_messages.TransformMessages(
            transforms=[
                name_transform
            ]
        )

# Add it to an agent so when they run inference it will apply to the messages
context_handling.add_to_agent(my_agent)

# Example
# Messages before
[
        {"role": "system", "content": "I am the system."},
        {"role": "user", "name": "charlie", "content": "I think the sky is blue."},
        {"role": "user", "name": "mary", "content": "The sky is red."},
        {"role": "user", "name": "bob", "content": "The sky is crimson."},
    ]

# Messages going into LLM (where name is removed, non-OpenAI clients)
[
        {"role": "system", "content": "I am the system."},
        {"role": "user", "content": "'charlie' said:\nI think the sky is blue."},
        {"role": "user", "content": "'mary' said:\nThe sky is red."},
        {"role": "user", "content": "'bob' said:\nThe sky is crimson."},
    ]
```

**Documentation to be done.**

## Dependency

For the GroupChat select speaker to be able to utilise this, PR #2719 needs to be merged first.

## Why are these changes needed?

To provide the necessary name context for non-OpenAI inference.

## Related issue number

PR #2719 

## Checks

- [X] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [X] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by thinkall — COMMENTED** [review]
Thank you @marklysze for the PR! Would like to add an example of using this new transform? What about updating an existing notebook and show the differences between with and  without this transform?

**Comment by marklysze** [comment]
> Thank you @marklysze for the PR! Would like to add an example of using this new transform? What about updating an existing notebook and show the differences between with and without this transform?

Thanks @thinkall, yep, definitely should. I'll put one together and add to the PR :).

**Comment by marklysze** [comment]
Just a note, @thinkall, I've asked @qingyun-wu to help with merging #2635 as that is a fix that will help make sure this work properly (as the name isn't included on the first message and that affects this transform's effectiveness). I'll keep working on the documentation.

**Comment by Hk669** [comment]
> Just a note, @thinkall, I've asked @qingyun-wu to help with merging #2635 as that is a fix that will help make sure this work properly (as the name isn't included on the first message and that affects this transform's effectiveness). I'll keep working on the documentation.

thanks for the PR @marklysze, we would love to see this working.

**Comment by marklysze** [comment]
Corrected link in documentation, I think everything looks like it's passing (OpenAI tests aside)... @thinkall anything else needed?

**Review by thinkall — APPROVED** [review]
Thank you @marklysze . LGTM!

**Pull request merged**
