### PR TITLE
[AutoGen Studio] Fix the new workflow process

### PR DESCRIPTION
**Pull request by shhdgit**
## Why are these changes needed?

Because the new workflow state is set to null, we are unable to add a new workflow again after editing or closing the workflow modal.

Before:

https://github.com/microsoft/autogen/assets/11549583/0d8c8bf0-8b66-4ec0-a030-c3347f4cefd4

After:

https://github.com/microsoft/autogen/assets/11549583/2a93be89-a2cf-415d-9e0e-a55bd09af16a

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by shhdgit** [comment]
@microsoft-github-policy-service agree

**Review by victordibia — CHANGES_REQUESTED** [review]
Thanks for finding this bug and suggesting a fix.
This PR makes changes to the convention used across multiple files (e.g., setWorkflow being renamed to saveWorflow).

Please consider limiting the change to removing `setWorkflow(null)`. We can  create a separate PR towards a general style refactor.

**Comment by shhdgit** [comment]
> Thanks for finding this bug and suggesting a fix. This PR makes changes to the convention used across multiple files (e.g., setWorkflow being renamed to saveWorflow).
> 
> Please consider limiting the change to removing `setWorkflow(null)`. We can create a separate PR towards a general style refactor.

Thank you for your advice! Do you mean something like the code snippet below?
```suggestion
  const defaultConfig = sampleWorkflowConfig();
  const [newWorkflow] = React.useState<IFlowConfig | null>(defaultConfig);
  
  ...
  
  const WorkflowModal = ({
    workflow,
    setWorkflow,
    showWorkflowModal,
    setShowWorkflowModal,
    handler,
  }: {
    workflow: IFlowConfig | null;
    setWorkflow?: (workflow: IFlowConfig | null) => void;
    showWorkflowModal: boolean;
    setShowWorkflowModal: (show: boolean) => void;
    handler?: (workflow: IFlowConfig) => void;
  }) => {
  
  ...
  
      <WorkflowModal
        workflow={newWorkflow}
        showWorkflowModal={showNewWorkflowModal}
        setShowWorkflowModal={setShowNewWorkflowModal}
        handler={(workflow: IFlowConfig) => {
          saveWorkFlow(workflow);
          setShowNewWorkflowModal(false);
        }}
      />
  ...
```

**Comment by shhdgit** [comment]
@victordibia PTAL, thanks!

**Review by victordibia — APPROVED** [review]
Thanks

**Pull request merged**
