### PR TITLE
Add MATH tests to testbed

### PR DESCRIPTION
**Pull request by kevin666aa**
## Why are these changes needed?

Add 17 level-5 problems from MATH to testbed.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by afourney** [comment]
Thanks. Looks great from what I can see. I'll formally test and review this ASAP.

**Comment by afourney** [comment]
Looks good. I was able to get everything to run. As we onboard more benchmarks, I might do some modifications to how requirements files are handled, but that's for a later time.

I left a few comments. Address them, and I'll approve.

**Comment by kevin666aa** [comment]
@afourney I didn't see any comments in the PR. Where do you put them?

**Comment by afourney** [comment]
@kevin666aa You don't see 4 comments in this thread? What about via this link: https://github.com/microsoft/autogen/pull/914/files/3f22352755910ce88178731d71c322dfc67e6b36
?

**Comment by kevin666aa** [comment]
> @kevin666aa You don't see 4 comments in this thread? What about via this link: https://github.com/microsoft/autogen/pull/914/files/3f22352755910ce88178731d71c322dfc67e6b36 ?

Emm.. This is so weird, I just don't see any comments, even through the link.

**Comment by afourney** [comment]
@kevin666aa That's so weird. Here are my comments: 
image

**Comment by skzhang1** [comment]
> @kevin666aa That's so weird. Here are my comments: image

You need to submit your comments. 
https://github.com/orgs/community/discussions/10369

**Comment by afourney** [comment]
Today I learned

**Review by afourney — APPROVED** [review]
LGTM

**Comment by afourney** [comment]
Update looks good. Approved

**Review by qingyun-wu — APPROVED** [review]

**Pull request merged**
