### PR TITLE
oai wrapper path fix 

### PR DESCRIPTION
**Pull request by Celestialchips**
## Why are these changes needed?

Corrected autogen oai path
from autogen import OpenAIWrapper

to

from autogen.oai.client import OpenAIWrapper

## Related issue number

 Closes issue #948

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Celestialchips** [comment]
@microsoft-github-policy-service agree

**Comment by afourney** [comment]
Are you by chance installing AutoGen via `pip install -e .`?

I find that these kinds of error are likely to occur when running code from the .`/autogen` root directory. It then gets confused if it should run from the `autogen` folder, or the installed library.

**Comment by Celestialchips** [comment]
No, I was using PyPi, `pip install autogen`. 

I also checked `./autogen` root directory to make sure it wasn't related to the issue.

**Comment by sonichi** [comment]
Please check my comment in #948

**Comment by ekzhu** [comment]
> No, I was using PyPi, `pip install autogen`.
> 
> I also checked `./autogen` root directory to make sure it wasn't related to the issue.

@Celestialchips could you try reinstall autogen and see if that solves this?

**Comment by rickyloynd-microsoft** [comment]
> > No, I was using PyPi, `pip install autogen`.
> > I also checked `./autogen` root directory to make sure it wasn't related to the issue.
> 
> @Celestialchips could you try reinstall autogen and see if that solves this?

`pip install pyautogen`

**Comment by Celestialchips** [comment]
looks fixed to me. The path is resolving correctly when calling

from autogen import config_list_from_json, UserProxyAgent

Sorry I haven't looked at this issue in a while I've been busy with some other projects.

Thanks!

**Comment by sonichi** [comment]
Thanks. Please feel free to reach out when you have more questions or feedback to share.

**Pull request closed without merging**
