### PR TITLE
Add Cerebras Integration

### PR DESCRIPTION
**Pull request by henrytwo**
## Why are these changes needed?

Add integration for Cerebras, which provides super low-latency, high speed LLM inference. Currently Llama 3.1-8B/70B are supported.

Tool calling examples have been provided in this PR, which also function with streaming. Additionally, token cost calculations have been implemented.

## Checks

- [X] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by henrytwo** [comment]
@microsoft-github-policy-service agree company="Cerebras"

**Comment by henrytwo** [comment]
cc: @marklysze, seems like you're working in this area of the codebase :)

**Comment by henrytwo** [comment]
Moved to https://github.com/autogen-ai/autogen/pull/48

**Comment by jackgerrits** [comment]
I see you closed this, did you still want us to review this?

**Comment by henrytwo** [comment]
> I see you closed this, did you still want us to review this? 

Yes I still want it to be reviewed, but I was told to open the PR in the Autogen org instead

**Comment by jackgerrits** [comment]
We'd be happy to review. Would you be able to reopen it so we're able to merge?

**Comment by henrytwo** [comment]
@jackgerrits it won't let me reopen this PR, but I opened another one here: https://github.com/microsoft/autogen/pull/3585

**Comment by jackgerrits** [comment]
Sounds good thanks!

**Pull request closed without merging**
