### PR TITLE
Updating Examples to follow new categorical structure. #273

### PR DESCRIPTION
**Pull request by rabbabansh**
## Why are these changes needed?

Addressing the remaining task for #273, I have copied over the changes from /Usecases to /Examples to follow the new categorical example notebooks structure. 

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by rabbabansh** [comment]
@microsoft-github-policy-service agree

**Comment by sonichi** [comment]
Could you please resolve the conflict with the main? Some new notebook is added.

**Review by rabbabansh — COMMENTED** [review]
added the new example notebook to make the docs upto date

**Comment by rabbabansh** [comment]
resolved the merge conflict

**Review by qingyun-wu — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
