### PR TITLE
Feat/headless browser (retargeted)

### PR DESCRIPTION
**Pull request by INF800**
## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by INF800** [comment]
There were some issues with headless tests. Fixed with [test: fix headless tests](https://github.com/INF800/autogen/commit/4097eabac696b1ca69f247be99468c2a3a06875f)

**Comment by INF800** [comment]
Added the headless example to the notebook as example 3. ChatResult is being returned by default in the latest version of initiate chat - this is making the notebook unreadable.

Other than this, added a new way to convert bing search page (from selenium) into text -  we can remove a lot of content by converting only the information with main tag.

**Comment by afourney** [comment]
@INF800 Looks great. Merged into headless_web_surfer. I will add my own PR on to this base, for additional format support and local file browsing. I probably won't get to that tonight though.

**Comment by afourney** [comment]
@INF800  Ok, I merged your work into the headless_web_surfer branch and created a PR that introduces some of my recent work on supporting multiple file formats and webpages in one common mdconvert utility. It also adds local file browsing and find-in-page support. 

More work to do, for sure. And, as noted earlier, I think we might try using Playwright rather than Selenium for file-downloading support.

**Pull request merged**
