### PR TITLE
Added Hindi Translation 

### LINKED ISSUE #332: Any Other language translated README
I am able create in 4 different languages
- Japanese
- Chinese
- German
- Hindi

### PR DESCRIPTION
**Pull request by Durgesh4993**
## Why are these changes needed?
They help to understand documentation in Hindi language

## Screenshot:

image

---

image

 

## Related issue number
Closes #332

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Durgesh4993** [comment]
Demo Video:

https://github.com/microsoft/autogen/assets/98798977/b8a07d50-b961-42c8-99fc-c8eb92f82952

**Review by gagb — COMMENTED** [review]
Thank you for the PR! 

@sonichi, I don't have the skills to verify a technical document written in Hindi... But like @pcdeadeasy said, we need to figure out our policy for READMEs in different language and whether we want to support them. A big issue is that while these are great for making the repo accessible to more people we will have to sync changes between all translations and the root README. It maybe better for users to use auto translation in their browsers instead....

**Comment by sonichi** [comment]
What @gagb said makes sense. @Durgesh4993 what do you think about having users to use auto translation in browsers?

**Review by pcdeadeasy — COMMENTED** [review]
@Durgesh4993, if you are able to get a decent translation using the browser, would it be ok to close the issues?

**Comment by gagb** [comment]
Closing this PR for now because we are unlikely to support this. Happy to reopen if we decide otherwise.

**Pull request closed without merging**
