### PR TITLE
Fix to issue #3295 related to Anthropic bedrock

### PR DESCRIPTION
**Pull request by makkzone**
## Why are these changes needed?
This change will allow session token to be included in the request to anthropic via amazon bedrock.

## Related PR number

#3210

## Related issue number
#3295 

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Hk669** [comment]
@makkzone have you tested this?

**Comment by sonichi** [comment]
@marklysze could you find previous contributors to this feature and add them as reviewers?

**Comment by makkzone** [comment]
Addressed the format issue and executed pre commit. All looks good.

**Review by marklysze — APPROVED** [review]
Thanks @makkzone, looks good.

**Pull request merged**
