### PR TITLE
code_executor in conversable agent interface

### PR DESCRIPTION
**Pull request by jackgerrits**
## Why are these changes needed?

The proposed move is to move towards prioritizing object based configuration of code execution. This allows for greater flexibility and control. It also reduces the surface area of configuration and is more discoverable.

```python
with DockerJupyterServer() as server:
    current = ConversableAgent(
        "current",
        code_execution_config={"executor": JupyterCodeExecutor(jupyter_server=server), "last_n_messages": 1}
    )

    proposed = ConversableAgent(
        "proposed",
        code_executor=JupyterCodeExecutor(jupyter_server=server),
        code_lookback_messages=1
    )
```

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by IANTHEREAL** [comment]
I'd like to ask if there's any chance that code_execution_config could be completely deprecated?

**Comment by IANTHEREAL** [comment]
Your change is good. If the newly added parameters do not coexist with `code_execution_config` in the future, that will be acceptable to me. Otherwise, the code could become overly complicated for developers.

**Comment by davorrunje** [comment]
Looks very good to me. We need to reduce the number of configs for sure, this is a step in the right direction.

**Comment by sonichi** [comment]
This is a good direction but I wonder whether it's the right timing. The new executors are introduced fairly new and there are many uncertainties about what the right settings should be exactly. I don't want to make this breaking change until we are sure these are the parameters to stay for a long time.

**Comment by jackgerrits** [comment]
Using the new executors is already a change from the old way of code execution. So this is a question of how does a user use the new executor? The proposal is to use this opportunity to move new usage to this added parameter. It's only a breaking change for the last_n_messages option which I think is rarely used anyway?

If a user wanted to use executors they need to change their code no matter what (`code_execution_config={"executor":foo}` vs `code_executor=foo`, so this is just pushing us towards how we want it to work going forward

**Comment by ekzhu** [comment]
Some contexts:
1. The usage of the new executors are not documented anywhere
2. This PR does not break existing usages, legacy or the `code_execution_config={"executor": executor}` style, I believe.
3. The new tutorial PR (#1702) still documents the legacy executor (docker and no docker).

**Comment by jackgerrits** [comment]
We are going to come back to this once we work out how code executors and function/tool calling works together.

**Comment by jackgerrits** [comment]
Closing as we've moved forward with the "executor" field, can revisit later as part of larger changes if it makes sense

**Pull request closed without merging**
