### PR TITLE
Fix for Anthropic client class so system messages aren't lost

### PR DESCRIPTION
**Pull request by marklysze**
At the moment if the set of messages for inference has more than one system message, only the last system message will be put into the Anthropic API `system` parameter.

During some testing of group chats I noticed there are multiple system messages for speaker selection in auto mode. So this meant the speaker selection was losing context and failing.

This PR simply concatenates the system messages together and it proves effective.

## Why are these changes needed?

Group Chat doesn't work effectively with Anthropic models when in auto mode without it.

## Related issue number

None raised.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by marklysze** [comment]
> looks clean. thanks @marklysze

Thanks @Hk669!

**Comment by randombet** [comment]
LGTM

**Review by thinkall — APPROVED** [review]
Thank you @marklysze for the PR! LGTM.

**Comment by thinkall** [comment]
There are errors in the openai tests. @marklysze

**Comment by marklysze** [comment]
> There are errors in the openai tests. @marklysze

Hi @thinkall, I don't believe the OpenAI tests are required for this PR and I believe they are throwing the error:
```
if not skip_openai:
    config_list = autogen.config_list_from_json(
```

I'm not clear on how to bypass them for the checks.

The exception is related to a missing `notebook/OAI_CONFIG_LIST` file.

**Pull request merged**
