### PR TITLE
Update function call doc with example of not using decorator syntax.

### PR DESCRIPTION
**Pull request by ekzhu**
## Why are these changes needed?

Update function call doc with example of not using decorator syntax, as many users are not familiar with decorators.

## Related issue number

#1213

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by davorrunje — APPROVED** [review]

**Comment by namanbarkiya** [comment]
how about adding a notebook example?.. can I add that?

**Comment by davorrunje** [comment]
@namanbarkiya there are three notebooks demonstrating how to register functions using decorators (one with currency calculator, one with sync and one with async example). It would be great if you could add an example of using decorators as functions to each of them.

**Comment by namanbarkiya** [comment]
@davorrunje so I should update the changes in all the 3 files, correct? (append the method in each notebook)

**Comment by ekzhu** [comment]
> @davorrunje so I should update the changes in all the 3 files, correct? (append the method in each notebook)

yes, you can start a new PR for this

**Comment by davorrunje** [comment]
@namanbarkiya actually, I added another utility method and updated everything in #1443. There was another problem I was fixing and just added those few lines while I was at it anyway. Thanx for the help in any case 😃

**Comment by namanbarkiya** [comment]
No worries! I'll try resolving some other issues, hope I can contribute to this project! 😄

**Pull request merged**
