### PR TITLE
Add test for async group chat

### PR DESCRIPTION
**Pull request by tyler-suard-parker**
Issue #543 has been on hold  for 3 weeks, due to not having tests for groupchat.  I added a test for groupchat, so hopefully now we can use AutoGen to call OpenAI asynchronously.

- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by tyler-suard-parker** [comment]
@microsoft-github-policy-service agree [company="Parker Hannifin"]

**Comment by tyler-suard-parker** [comment]
@microsoft-github-policy-service agree company="Parker Hannifin"

**Comment by tyler-suard-parker** [comment]
@qingyun-wu @sonichi @kittyandrew

**Comment by qingyun-wu** [comment]
Could you run pre-commit to regulate code format? Thank you!

**Comment by tyler-suard-parker** [comment]
> Fixed code format issues. LGTM now! Thank!

I am very proud to be a contributor to such an important Microsoft repo!

**Comment by tyler-suard-parker** [comment]
@qingyun-wu I have some very bad news.  I just built autogen from source with the new merges and it is STILL not running async, at least for me.

**Pull request merged**
