### PR TITLE
Use AzureOpenAI in OpenAIWrapper

### PR DESCRIPTION
**Pull request by kevin666aa**
## Why are these changes needed?
Creating AzureOpenAI in OpenAIWrapper if api_type is "azure"

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by sonichi** [comment]
@kevin666aa if you'd like help with this PR, I'm happy to find helpers from discord.

**Comment by kevin666aa** [comment]
> @kevin666aa if you'd like help with this PR, I'm happy to find helpers from discord.

Yes, thanks!

**Comment by cforce** [comment]
@kevin666aa can you please rebase and and check tests afterwards 🙏

**Comment by kevin666aa** [comment]
@cforce This PR should be closed. The described feature is implemented in #1232.

**Pull request closed without merging**
