### PR TITLE
Fix website accessibility

### PR DESCRIPTION
**Pull request by cheng-tan**
## Why are these changes needed?
Fix accessibility issue for the website

TODO:
- [x] fix light theme accessibility issue
- [x] fix dark them accessibility issue

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by skzhang1** [comment]
The default appearance should not be dark. Can you change it to light? Thanks! @cheng-tan

**Comment by cheng-tan** [comment]
> The default appearance should not be dark. Can you change it to light? Thanks! @cheng-tan

Hi @skzhang1, is your system set to dark theme?

**Review by victordibia — APPROVED** [review]
Thanks for the color contrast fixes @cheng-tan!
I was able to run without any errors.
Looking good!

**Comment by skzhang1** [comment]
> > The default appearance should not be dark. Can you change it to light? Thanks! @cheng-tan
> 
> Hi @skzhang1, is your system set to dark theme? I didn't change the default color mode, so it should still be light

Today I learned. My system is dark theme.

**Review by skzhang1 — APPROVED** [review]

**Pull request merged**
