### PR TITLE
LLM Observability documentation fixes: Broken links, grammar, and spelling

### PR DESCRIPTION
**Pull request by areibman**
@qingyun-wu @ekzhu @sonichi 

## Why are these changes needed?

3 pages in the AutoGen documentation have clarity, spelling, and formatting issues. 

**1. Broken links**
https://microsoft.github.io/autogen/docs/notebooks/agentchat_agentops/ 

In the AgentChat AgentOps notebook, several images are not rendering because they point to invalid URLs:
image

We've replaced these URLs so they now render correctly by pointing to GitHub raw user content links.

**2. Updated the LLM Observability link for clarity:**

The current LLM Observability section doesn't do an adequate job explaining observability or why it's important. The English in this page has been updated to make it easier for developers to understand its purpose and the tools available in AutoGen to add observability.

**3. Updated the AgentOps example notebook**

Several images in this notebook were pointing to the wrong URL and were not rendering. Also updated text for clarity + removed an API key in the notebook

## Related issue number

Closes: #2994 

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by areibman** [comment]
@microsoft-github-policy-service agree [company=“{AgentOps}"]

**Comment by areibman** [comment]
> @areibman please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
>  > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="{AgentOps}"]

**Comment by areibman** [comment]
> #### ⚠️ GitGuardian has uncovered 2 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 
> GitGuardian id	GitGuardian status	Secret	Commit	Filename	
> [11616921](https://dashboard.gitguardian.com/workspace/221093/incidents/11616921)	Triggered	Generic High Entropy Secret	[4ddda11](https://github.com/microsoft/autogen/commit/4ddda116d5c70f5383f95818424bb450a45b2693)	notebook/agentchat_agentops.ipynb	[View secret](https://github.com/microsoft/autogen/commit/4ddda116d5c70f5383f95818424bb450a45b2693#diff-b63f23e062ab79e05d69e5d7ff31ab62e29d958237ef1807891be38056d2b90dR107)
> [11616921](https://dashboard.gitguardian.com/workspace/221093/incidents/11616921)	Triggered	Generic High Entropy Secret	[7afe9d9](https://github.com/microsoft/autogen/commit/7afe9d98aa0e34ab75231b485fa03ab8479a36a6)	notebook/agentchat_agentops.ipynb	[View secret](https://github.com/microsoft/autogen/commit/7afe9d98aa0e34ab75231b485fa03ab8479a36a6#diff-b63f23e062ab79e05d69e5d7ff31ab62e29d958237ef1807891be38056d2b90dR107)
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.

There are no secrets being leaked in this PR. They are false positives pointing to GUIDs in a few GitHub URLs
image

**Review by qingyun-wu — APPROVED** [review]
Thanks for the quick fix! Looks great!

**Pull request merged**
