### PR TITLE
Introducing Experimental GPT Assistant Agent  in AutoGen

### PR DESCRIPTION
**Pull request by IANTHEREAL**
## Why are these changes needed?

The GPT Assistant Agent is in its early stages and has been developed for experimental purposes. It's important to note that due to limitations with our current OpenAI account, testing has been somewhat restricted.

Despite these limitations, the GPT Assistant Agent can be utilized in its current form as follows:

```
from autogen.agentchat.contrib.gpt_assistant_agent import GPTAssistantAgent
from autogen import UserProxyAgent, ossinsight_api_schema

# Setup user proxy with no code execution config
user_proxy = UserProxyAgent(
    name="Admin",
    system_message="A human. Interact with the analyst to do data analysis.",
    code_execution_config=False,
)

# Initialize GPTAssistantAgent with Open Source Project Analyst role
analyst = GPTAssistantAgent(
    name="Open_Source_Project_Analyst",
    llm_config={
        "tools": [{"type": "function", "function": ossinsight_api_schema}]
    },
    instructions="Hello, Open Source Project Analyst. You'll conduct comprehensive evaluations of open source projects or organizations on the GitHub platform, analyzing project trajectories, contributor engagements, open source trends, and other vital parameters. Please carefully read the context of the conversation to identify the current analysis question or problem that needs addressing.",
)

# Register functions for data querying
analyst.register_function(
    function_map={
        "ossinsight_data_api": ask_ossinsight,
    }
)

# Begin chat interaction
user_proxy.initiate_chat(analyst, message="How many contributors does the TiDB project have?")

```

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by IANTHEREAL** [comment]
@microsoft-github-policy-service agree

**Comment by gagb** [comment]
Thank you! Reviewing this rn!

**Comment by gagb** [comment]
The same `GPTAssistant` maybe in a conversation with multiple agents at the same time, we need to use a dictionary that maps agents to threads (similar to chat history), instead of using a single fixed thread.

**Comment by gagb** [comment]
@IANTHEREAL can you add me as a collaborator in your fork? I can push commits for my suggestions :)

**Comment by sonichi** [comment]
@BeibinLi did you make an update to README which conflicts with the main? Also, shall we say "experimental support"?

**Comment by IANTHEREAL** [comment]
@gagb I encountered difficulties yesterday due to rate limits, which prevented me from conducting more tests. I believe that GPT-4 Turbo supports a longer window. To determine if providing all session data would yield better results from the agent, I opted to use a single thread.   But I'm not opposed to your suggestions. I think we can first adhere to the previous design, and I will do further verification by myself.

At the same time, I have already invite you as a collaborator. Thank you very much for your collaboration

**Comment by IANTHEREAL** [comment]
@gagb But if the idea is to have the agent act as a service, providing multiple conversations with different contexts simultaneously. How do you think about it?

 If that's the case, it indeed needs support. And I am working on it now.

**Comment by IANTHEREAL** [comment]
@gagb @sonichi @BeibinLi  PTAL. If there are no concerns, I suggest we merge it as soon as possible. I will continue testing and further strengthening it in the meantime.

**Comment by gagb** [comment]
> @gagb @sonichi @BeibinLi PTAL. If there are no concerns, I suggest we merge it as soon as possible. I will continue testing and further strengthening it in the meantime.

Yes lets merge it and I can document issues/improvements and we can fix them one by one faster after merge.

**Comment by gagb** [comment]
> @gagb But if the idea is to have the agent act as a service, providing multiple conversations with different contexts simultaneously. How do you think about it?
> 
> If that's the case, it indeed needs support. And I am working on it now.

Yes, I think of the threads as very similar to chat history that AutoGen maintains, which has been pretty a useful abstraction.

**Review by gagb — APPROVED** [review]

**Review by LeoLjl — APPROVED** [review]
LGTM

**Review by BeibinLi — APPROVED** [review]
LGTM. We may want to add a notebook soon to show an example how to use the agent.

**Comment by sonichi** [comment]
The test failed: https://github.com/microsoft/autogen/actions/runs/6832796621/job/18583868663?pr=616#step:7:456
We need to fix it before merging.

**Comment by sonichi** [comment]
@kevin666aa could you check the test error for CompressibleAgent? https://github.com/microsoft/autogen/actions/runs/6832796621/job/18583868663?pr=616

**Comment by sonichi** [comment]
merging because the compressible agent test error doesn't seem to be introduced by this PR. @kevin666aa please fix the error in a separate PR or create an issue.

**Comment by kevin666aa** [comment]
> @kevin666aa could you check the test error for CompressibleAgent? https://github.com/microsoft/autogen/actions/runs/6832796621/job/18583868663?pr=616

Got it!

**Comment by aignise** [comment]
How does one retrieve existing GPTs created on openai website using their ids?

**Pull request merged**
