### PR TITLE
Add dev container for AutoGen Studio

### PR DESCRIPTION
**Pull request by gagb**
Solution:
Create a subdirectory called `.devcontainer/studio` with correct `Dockerfile` and `devcontainer.json`.
I reused the Dockerfile from `.devcontainer` and modified the `devcontainer.json` to follow instructions from AutoGen Studios README.

I tested this container with GitHub Codespaces.
 
## Why are these changes needed?
We need to add a dev container for AutoGen Studio

## Related issue number

#1224 

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by gagb** [comment]
@victordibia I need your help to add a relevant reviewer to this PR.

**Comment by sonichi** [comment]
How do we use it? If I open a GitHub codespace I don't get to choose which Dockerfile to use, do I?

**Comment by gagb** [comment]
> How do we use it? If I open a GitHub codespace I don't get to choose which Dockerfile to use, do I?

Use the "new with options" 

image

**Review by victordibia — APPROVED** [review]
Thanks! I confirm I tested this and it works correctly.
I was able to launch a dev container on GH codespaces and autogenstudio was available on the terminal.

**Comment by sonichi** [comment]
> > How do we use it? If I open a GitHub codespace I don't get to choose which Dockerfile to use, do I?
> 
> Use the "new with options"
> 
> image

Thanks. Could you add this info to documentation?

**Review by qingyun-wu — APPROVED** [review]
LGTM except that documentation is missing. I am fine merging this PR. We could add documentation in a separate PR.

**Comment by gagb** [comment]
> LGTM except that documentation is missing. I am fine merging this PR. We could add documentation in a separate PR.

Ty, working on that issue

**Pull request merged**
