### PR TITLE
Remove system message from code executors

### PR DESCRIPTION
**Pull request by jackgerrits**
https://github.com/microsoft/autogen/pull/1835 but from main repo

Closes https://github.com/microsoft/autogen/issues/1684

### CODE REVIEW

**Comment by ekzhu** [comment]
@cheng-tan Do you know why this test fails? https://github.com/microsoft/autogen/actions/runs/8217196757/job/22472634040?pr=1933.

**Comment by sonichi** [comment]
@cheng-tan could you check the failing test for logging: https://github.com/microsoft/autogen/actions/runs/8217196757/job/22472634040?pr=1933

**Review by ekzhu — APPROVED** [review]

**Comment by ekzhu** [comment]
This PR shouldn't need OpenAI tests, as it actually removes some Open AI tests.

**Comment by sonichi** [comment]
> This PR shouldn't need OpenAI tests, as it actually removes some Open AI tests.

The test is taking an oddly long time. There may be something wrong.

**Comment by sonichi** [comment]
> > This PR shouldn't need OpenAI tests, as it actually removes some Open AI tests.
> 
> The test is taking an oddly long time. There may be something wrong.

I canceled the test in case there is a test that keeps requesting OpenAI. Has anyone run the test locally?

**Comment by ekzhu** [comment]
> > > This PR shouldn't need OpenAI tests, as it actually removes some Open AI tests.
> > 
> > 
> > The test is taking an oddly long time. There may be something wrong.
> 
> I canceled the test in case there is a test that keeps requesting OpenAI. Has anyone run the test locally?

I haven't experienced any problem running locally. I am using open ai endpoint.

**Pull request merged**
