### PR TITLE
fix `ImportFromModule` is unhashable issue

### LINKED ISSUE #3361: [Bug]: TypeError: unhashable type: 'ImportFromModule' for User Defined Functions
### Describe the bug

I got this error when I created a user defined function:
`TypeError: unhashable type: 'ImportFromModule'`

### Steps to reproduce

My function is like this:
```
@with_requirements(python_packages=["requests", "urllib3"], global_imports=["requests", "os", ImportFromModule("urllib.parse", ["urlencode"])])
def search_from_web(search_keyword: str):
    pass
```

The exception is caused by this function under `func_with_reqs.py`:
```
def _build_python_functions_file(
    funcs: List[Union[FunctionWithRequirements[Any, P], Callable[..., Any], FunctionWithRequirementsStr]]
) -> str:
    # First collect all global imports
    global_imports = set()
    for func in funcs:
        if isinstance(func, (FunctionWithRequirements, FunctionWithRequirementsStr)):
            global_imports.update(func.global_imports)

    content = "\n".join(map(_import_to_str, global_imports)) + "\n\n"

    for func in funcs:
        content += _to_code(func) + "\n\n"

    return content
```

The `ImportFromModule` is unhashable at `global_imports.update(func.global_imports)`

### Model Used

gpt-4o-mini

### Expected Behavior

_No response_

### Screenshots and logs

> Traceback (most recent call last):
  File "C:\Users\zhaoc\PycharmProjects\financal-analyst\3.function_use.py", line 15, in <module>
    code_executor.initiate_chat(
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 1019, in initiate_chat
    self.send(msg2send, recipient, silent=silent)
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 656, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 821, in receive
    self.send(reply, sender, silent=silent)
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 656, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 819, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 1973, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 1471, in _generate_code_execution_reply_using_executor
    code_result = self._code_executor.execute_code_blocks(code_blocks)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\coding\local_commandline_code_executor.py", line 245, in execute_code_blocks
    self._setup_functions()
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\coding\local_commandline_code_executor.py", line 207, in _setup_functions
    func_file_content = _build_python_functions_file(self._functions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaoc\miniconda3\envs\financial-analyst\Lib\site-packages\autogen\coding\func_with_reqs.py", line 165, in _build_python_functions_file
    global_imports.update(func.global_imports)
TypeError: unhashable type: 'ImportFromModule'

### PR DESCRIPTION
**Pull request by zcipod**
This fix makes the conversion to string prior to the deduplication to avoid this issue

## Why are these changes needed?
When create user defined functions, an exception occurs because of the deduplication of ImportFromModule
This fix makes the conversion to string prior to the deduplication to avoid this issue

## Related issue number
Closes #3361

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by thinkall — APPROVED** [review]
Thank you @zcipod for the PR! LGTM.

**Review by thinkall — COMMENTED** [review]
Could you please fix the type check error? Thanks.

**Comment by zcipod** [comment]
> Could you please fix the type check error? Thanks.

Sorry for late response.
Type annotation for `global_imports` has been added
thanks @thinkall

**Review by skzhang1 — APPROVED** [review]

**Review by thinkall — COMMENTED** [review]
Hi @zcipod , could you please run pre-commit to fix the code format issue? Thanks. https://microsoft.github.io/autogen/docs/contributor-guide/pre-commit

**Comment by zcipod** [comment]
Hi @jackgerrits @qingyun-wu,

Could you please have a review of this PR? Thanks!

**Pull request merged**
