### PR TITLE
Add a GPT-based implementation of profiler

### PR DESCRIPTION
**Pull request by gagb**
## Why are these changes needed?

Input: conversation log, possible codes (and guidelines)
Output: labelled log + visualization

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by afourney** [comment]
Sounds intriguing. Let me take a look ASAP.

**Comment by gagb** [comment]
> Sounds intriguing. Let me take a look ASAP.

Still a draft! Don't review yet! I will send updatesw when its ready for review. Also need to base it on merged testbed branch

**Comment by afourney** [comment]
Sounds good.

Let me know how/when to dive in.

**Comment by gagb** [comment]
Outdated, will address in a different PR.

**Pull request closed without merging**
