### PR TITLE
Feature: Add ability to use a separate python environment in local executor

### PR DESCRIPTION
**Pull request by Gr3atWh173**
## Why are these changes needed?

To execute code inside a python virtual environment so that the base environment isn't polluted by unwanted dependencies.

## Related issue number

Solves #2613 

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Gr3atWh173** [comment]
@microsoft-github-policy-service agree

**Review by ekzhu — COMMENTED** [review]
Shall we update the `execution_policies` argument so it can supply the executable binary for Python?

**Comment by Gr3atWh173** [comment]
Right now an execution policy is defined as a `str` to `bool` mapping. I think it will be a breaking change to change its type. IMO a better solution is to pass a [environment `context` object to the executor](https://docs.python.org/3/library/venv.html#venv.EnvBuilder.ensure_directories). It won't break existing code that depends on Autogen and solve the issues I'm having with handling different `venv` directory structures for Windows and Unix systems.

**Comment by Gr3atWh173** [comment]
Needed to add a special case for Windows because of how `CreateProcessW()` works internally. Here's a good explainer on why adding the interpreter to PATH was not working: https://github.com/python/cpython/issues/105889#issuecomment-1595930855

**Review by ekzhu — COMMENTED** [review]
Thanks for the PR!  A few questions:

1. Does this only work with Python virtual environment not Anaconda?
2. Can you add a code block example in the doc string for how to use the `virtual_env_context` argument? 
3. Can you update the documentation in `website/docs/topics/code-execution/cli-code-executor.ipynb` for an example on how to use this?

**Comment by Gr3atWh173** [comment]
I don't think these changes will work with Anaconda since it doesn't use `venv` to manage environments IIRC

**Review by ekzhu — APPROVED** [review]

**Comment by ekzhu** [comment]
Thanks @Gr3atWh173 can you add your discord handle so we can connect with you on AutoGen's discord server: #2310

**Pull request merged**
