### PR TITLE
Fix Anthropic Bedrock support

### PR DESCRIPTION
**Pull request by joris-swapfiets**
## Why are these changes needed?

The current implementation of `AnthropicBedrock` as created by @makkzone [here](https://github.com/microsoft/autogen/pull/3103) does not properly add the AWS variables to the `openai_config`. Resulting in the following error:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "autogen/autogen_test.py", line 43, in <module>
    classifier = ConversableAgent(
  File "autogen/agentchat/conversable_agent.py", line 159, in __init__
    self._validate_llm_config(llm_config)
  File "autogen/agentchat/conversable_agent.py", line 263, in _validate_llm_config
    self.client = None if self.llm_config is False else OpenAIWrapper(**self.llm_config)
  File "autogen/oai/client.py", line 422, in __init__
    self._register_default_client(config, openai_config)  # could modify the config
  File "autogen/oai/client.py", line 501, in _register_default_client
    client = AnthropicClient(**openai_config)
  File "autogen/oai/anthropic.py", line 114, in __init__
    raise ValueError("API key or AWS credentials are required to use the Anthropic API.")
ValueError: API key or AWS credentials are required to use the Anthropic API.
```

This change introduces the `_configure_openai_config_for_bedrock` method to include the necessary AWS variables (`aws_access_key`, `aws_secret_key`, `aws_session_token`, and `aws_region`) in `openai_config` if no `api_key` is present in the `config` and the `api_type` startswith `anthropic`. This ensures that the `AnthropicBedrock` client can be set correctly and function as expected.

## Related PR number

https://github.com/microsoft/autogen/pull/3103

## Related issue number

Closes [#1234](https://github.com/microsoft/autogen/issues/339)

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. 
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Hk669** [comment]
@joris-swapfiets can you remove the check for the `aws_session_token`, i think it is not necessary(Optional)

**Comment by joris-swapfiets** [comment]
@Hk669 Done!

**Comment by Hk669** [comment]
> @Hk669 Done!

also from the `AnthropicClient`, where there is a check for the session_key. thanks

**Comment by joris-swapfiets** [comment]
@microsoft-github-policy-service agree

**Comment by joris-swapfiets** [comment]
@Hk669 Did you mean the check I just commited or something else?

**Comment by Hk669** [comment]
> @Hk669 Did you mean the removal of the check I just committed or removal of all instances of the `aws_session_token` from `AnthropicClient`

image
you can use this for reference.

**Comment by joris-swapfiets** [comment]
@Hk669 Removed it based on your reference

**Review by makkzone — COMMENTED** [review]
Looks good to me. Thanks you @joris-swapfiets for the changes.

**Comment by Hk669** [comment]
> @Hk669 Removed it based on your reference

can you run `pre-commit` to fix the formatting check.

**Comment by joris-swapfiets** [comment]
Running pre-commit now

**Review by Hk669 — APPROVED** [review]
looks good to me. thanks for the PR @joris-swapfiets

**Comment by Hk669** [comment]
this should fix the issue #3198

**Comment by billdoors** [comment]
I double checked that my access key, secret key and session token are working using AnthropicBedrock module. But I get the following error after I use autogen. 


---------------------------------------------------------------------------
PermissionDeniedError                     Traceback (most recent call last)
Cell In [28], [line 22](vscode-notebook-cell:?execution_count=28&line=22)
     [15](vscode-notebook-cell:?execution_count=28&line=15) assistant = autogen.AssistantAgent("assistant", llm_config={"config_list": config_list})
     [17](vscode-notebook-cell:?execution_count=28&line=17) support_request = {
     [18](vscode-notebook-cell:?execution_count=28&line=18)         "content": "I am unable to install the latest update of the software.",
     [19](vscode-notebook-cell:?execution_count=28&line=19)         "role": "user"
     [20](vscode-notebook-cell:?execution_count=28&line=20)     }
---> [22](vscode-notebook-cell:?execution_count=28&line=22) assistant.generate_reply(messages=[support_request])

File ~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1973, in ConversableAgent.generate_reply(self, messages, sender, **kwargs)
   [1971](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1971)     continue
   [1972](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1972) if self._match_trigger(reply_func_tuple["trigger"], sender):
-> [1973](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1973)     final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
   [1974](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1974)     if logging_enabled():
   [1975](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1975)         log_event(
   [1976](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1976)             self,
   [1977](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1977)             "reply_func_executed",
   (...)
   [1981](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1981)             reply=reply,
   [1982](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1982)         )

File ~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1341, in ConversableAgent.generate_oai_reply(self, messages, sender, config)
   [1339](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1339) if messages is None:
   [1340](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/autogen/agentchat/conversable_agent.py:1340)     messages = self._oai_messages[sender]
...
   (...)
   [1053](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/anthropic/_base_client.py:1053)     stream_cls=stream_cls,
   [1054](https://file+.vscode-resource.vscode-cdn.net/Users/qqnl/Library/CloudStorage/WorkDocsDrive-Documents/Gitlab/agent%20study/~/Library/Python/3.9/lib/python/site-packages/anthropic/_base_client.py:1054) )

PermissionDeniedError: Error code: 403 - {'message': 'The security token included in the request is invalid.'}

**Comment by makkzone** [comment]
@billdoors  Can you post your code which you tried to execute?

**Comment by billdoors** [comment]
@makkzone code is posted in this issue report: https://github.com/microsoft/autogen/issues/3295

**Pull request merged**
