### PR TITLE
feat(studio): Anthropic + AnthropicBedrock support

### PR DESCRIPTION
**Pull request by JGalego**
## Why are these changes needed?

This PR adds support for Anthropic models via [Anthropic API](https://www.anthropic.com/api) or [Amazon Bedrock](https://aws.amazon.com/bedrock/claude) (relies on https://github.com/microsoft/autogen/pull/3103).

**Demo:** [Travel Agent workflow with Claude 3 Haiku via Amazon Bedrock 🧳🗺️⁀જ✈🏝️🍹🌞🌊](https://youtu.be/SSpkJzkExek)

autogenstudio_anthropic

## Related issue number

N/A

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by marklysze** [comment]
Thanks, happy to review this one if you can add me as a reviewer :)

**Comment by JGalego** [comment]
> Thanks, happy to review this one if you can add me as a reviewer :)

Don't have enough permissions to request a review @victordibia @qingyun-wu

**Comment by marklysze** [comment]
> > Thanks, happy to review this one if you can add me as a reviewer :)
> 
> Don't have enough permissions to request a review @victordibia @qingyun-wu

All good, I'll add myself and give it a test :)

**Review by marklysze — APPROVED** [review]
@JGalego, thanks for introducing Anthropic to studio. I have incorporated your code and have been able to successfully create models and test them, both with authentication against Anthropic's cloud inference and Amazon's Bedrock, nice one :).

I'm not an expert on autogenstudio development so I haven't tested further than that and I can approve on this basis. @victordibia, if you get a chance it would be good to get your review as well :).

**Comment by gagb** [comment]
@JGalego @marklysze -- Victor was on a vacation. I am sure he will review it this week :) :) Thanks for the PR.

**Comment by JGalego** [comment]
@victordibia just noticed this PR was closed without merging - why was that?

**Comment by rafael-bianchi** [comment]
@victordibia any chance we get this PR?

**Pull request closed without merging**
