### PR TITLE
bulk update copyright - issue #3930

### LINKED ISSUE #3930: add Microsoft headers everywhere
### What happened?

we need to comply and use msft standard headers/copyright everywhere

### What did you expect to happen?

follow policy

### How can we reproduce it (as minimally and precisely as possible)?

NA

### AutoGen version

0.4

### Which package was this bug in

Core

### Model used

_No response_

### Python version

_No response_

### Operating system

_No response_

### Any additional info you think would be helpful for fixing this bug

_No response_

### PR DESCRIPTION
**Pull request by rysweet**
using vs code add msft copyright header everywhere the language server suggested across the whole solution. 
closes #3930

### CODE REVIEW

**Comment by rysweet** [comment]
@LittleLittleCloud 
I noticed that the remediation proposed by vs code changed the headers on the files that already had some and remove the lines that had the file name in comments. I'm not sure why those there there or if some tooling needs it. Also unclear on importance of difference between "Microsoft Corporation" and "Microsoft" - I just accepted whatever VS Code proposed. Let me know if it needs to be more tuned.

**Comment by LittleLittleCloud** [comment]
@rysweet 
You might need to also update this `.editorconfig`?

https://github.com/microsoft/autogen/blob/525546f45dd613eaedf39f2b08bf384865f19e83/dotnet/.editorconfig#L197

**Comment by LittleLittleCloud** [comment]
@rysweet Are you still going to merge this?

**Comment by rysweet** [comment]
> @rysweet Are you still going to merge this?

@LittleLittleCloud - do you know if there is official devdiv or other guidance on what we should use here?

**Comment by LittleLittleCloud** [comment]
> Perhaps we should also update to include the license then?

Yes that make sense

**Comment by rysweet** [comment]
can reopen as a new PR later after we agree on the header

**Pull request closed without merging**
