### PR TITLE
Update FAQ.md with api_base vs base_url question

### PR DESCRIPTION
**Pull request by gagb**
## Why are these changes needed?
added a faq for api_base vs base_url because people were asking about it frequently.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by rickyloynd-microsoft — APPROVED** [review]
Very nice!

**Comment by sonichi** [comment]
Do we need it given:
https://microsoft.github.io/autogen/docs/Installation#migration-guide-to-v02
?

**Comment by rickyloynd-microsoft** [comment]
> Do we need it given: https://microsoft.github.io/autogen/docs/Installation#migration-guide-to-v02 ?

I think the repetition is helpful for people who don't carefully read or remember the migration guide, and people who pick up an old piece of code from somewhere without realizing there was an API migration.

**Review by BeibinLi — APPROVED** [review]
LGTM.

**Comment by BeibinLi** [comment]
Alternatively, should we check "api_base" and "base_url" in the config dictionary, and decide which one to use based on the OpenAI Version?

**Comment by sonichi** [comment]
> > Do we need it given: https://microsoft.github.io/autogen/docs/Installation#migration-guide-to-v02 ?
> 
> I think the repetition is helpful for people who don't carefully read or remember the migration guide, and people who pick up an old piece of code from somewhere without realizing there was an API migration.

How about adding a link to the migration guide page too?

**Comment by sonichi** [comment]
> Alternatively, should we check "api_base" and "base_url" in the config dictionary, and decide which one to use based on the OpenAI Version?

That's also a good idea.

**Review by afourney — APPROVED** [review]

**Pull request merged**
