### PR TITLE
Add StateFlow

### PR DESCRIPTION
**Pull request by kevin666aa**
## Why are these changes needed?

Introduce the StateFlow feature, which allows users to build workflows with AutoGen agents from a state-oriented perspective.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by radman-x** [comment]
Would also like to support switching back and forth between stateflow and groupchat to allow more free flowpwing collaboration sometimes. Any thoughts/code on how to do this?

**Comment by qingyun-wu** [comment]
Closing this PR to avoid confusion! @radman-x thank you for your comment and you can reach out to @kevin666aa directly for more discussions.

**Comment by radman-x** [comment]
@kevin666aa @qingyun-wu Is this supplanted by nested chats?

**Comment by kevin666aa** [comment]
> @kevin666aa @qingyun-wu Is this supplanted by nested chats?

No, this is not supplanted by nested chats. This PR is attempting to introduce a completely new concept and still needs discussion. Currently, it is best to accomplish the idea with groupchat, with customized functions from https://github.com/microsoft/autogen/pull/1791. 

If you like the idea and would like to discuss, we can discuss on discord! My username is kevinwyr

**Pull request closed without merging**
