### PR TITLE
Override OpenAIWrapper | hook streams and other client mechanisms

### LINKED ISSUE #1199: Support for WebSockets, streaming responses to a frontend [Feature Request]:
### Is your feature request related to a problem? Please describe.

I am using a Microsoft Teams App for a frontend, and hosting Autogen on my backend.  When I send a message to Autogen from my frontend, Autogen does some processing and then sends back the final answer.  This can take up to 2 minutes, which is too long for my customers.  The vast majority of that time is taken up by GPT-4 generating an answer.  I would like it if the final answer generated by Autogen could be streamed back to the frontend, using websockets or another protocol that is compatible with Microsoft Teams Apps.  This would give my users something to look at immediately, rather than waiting a long time for the complete answer to pop up.

### Describe the solution you'd like

An easy, plug-and-play solution for Microsoft Teams Apps, that allows Autogen to stream information to the Teams App.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bitnom**
## Why are these changes needed?

Give end-developers a way to hook the openai wrapper without having to duplicate huge blocks of code. This can be used to easily hook streamed responses with a generator. Now it is relatively painless to override `client.chat.completions.create` for instance.

I do realize [Custom Client support #831](https://github.com/microsoft/autogen/pull/831) exists. This PR is something I implemented to accomplish a goal ahead of such merges, and so I share.

## Related issues

#1199 and probably others. A follow-up PR for passing arbitrary data from request messages through to their responses will be a better moment to go around closing issues where hooks have been requested. I will make that PR encompass as many of those issues as possible by also supporting callbacks, which is currently in the works.

There are many related issues and ongoing works. I'll just reference #217 for brevity.

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by ekzhu** [comment]
Thanks for the PR! I think this is very much inline with the custom client effort @olgavrou is doing also with the discussion @davorrunje and I had in #1227. I am wondering if you are interested in continuing the work in #831? We can have a new PR as the old one seems quite outdated.

**Comment by bitnom** [comment]
> Thanks for the PR! I think this is very much inline with the custom client effort @olgavrou is doing also with the discussion @davorrunje and I had in #1227. I am wondering if you are interested in continuing the work in #831? We can have a new PR as the old one seems quite outdated.

np. Sure, I'll do it. I have continue in this vein anyway for my work.

I'll make a new issue and/or draft outlining what should be done, and continue from there. We need to be able to pass arbitrary data from any initiating message through to its response(s).

**Comment by bitnom** [comment]
I presume somebody is going to ask me to write a test here. I have been using the PR with success for a few days, and will add a test shortly.

**Comment by bitnom** [comment]
For anyone coming here from other PRs/issues looking for various forms of overrides and hooks, it looks like the major effort for that will be: https://github.com/microsoft/autogen/pull/1240

**Comment by ekzhu** [comment]
> I presume somebody is going to ask me to write a test here. I have been using the PR with success for a few days, and will add a test shortly.

Let's focus on working on this #1240 first? Regarding wrapper client we have many hands already.

**Comment by ekzhu** [comment]
@bitnom There have been many recent changes e.g., the custom client and recent work on streming #1551. Do you still want to pursue this PR?

**Comment by bitnom** [comment]
> @bitnom There have been many recent changes e.g., the custom client and recent work on streming #1551. Do you still want to pursue this PR?

I'll be getting back to autogen PRs this weekend, and will re-evaluate my PRs and issues at that point. Other work had taken me out of it for a bit. I still think it's important to be able to override but I need to get caught-up and see where everything is at.

IOStream / https://github.com/microsoft/autogen/pull/1551 seems a good idea in its goal. I would just caution that it should probably be protocol agnostic (Without websockets). We have (In our programming arsenal) notions of queues, backpressure, channels, etc, and thread-safety for them. I think the protocol used at the edge of the module for IO should be an implementation detail left up to the end-user-programmer. Queues are dead-simple. Note that I haven't actually reviewed the iostream code yet (Will have time in a few days) so maybe it already addresses this.

@davorrunje

**Comment by gagb** [comment]
Closing because of inactivity. Please reopen if you need these changes.

**Pull request closed without merging**
