### PR TITLE
Fixtest

### PR DESCRIPTION
**Pull request by Josephrp**

### CODE REVIEW

**Comment by gagb** [comment]
@Josephrp -- is this PR still of interest to you? If yes, can you please improve description so that we can understand it.

**Comment by Josephrp** [comment]
> @Josephrp -- is this PR still of interest to you? If yes, can you please improve description so that we can understand it.

sure thing , will keep at it to make a microsoft model studio client with github pat accordingly :-)

**Comment by gagb** [comment]
@Josephrp -- can you please update the description if you'd like this PR to be reviewed?

**Comment by Josephrp** [comment]
yes , with all my appologies , getting back to work after some time :-)

**Comment by jackgerrits** [comment]
@Josephrp is this superseded by #3559?

**Comment by jackgerrits** [comment]
Feel free to reopen if this is different to the above mentioned PR

**Pull request closed without merging**
