### PR TITLE
improve test speed

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

accelerate openai CI.
addressing the 10 slowest in https://github.com/microsoft/autogen/actions/runs/8714899367/job/23905894422?pr=2313
reducing from 82m to 11m.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Hk669** [comment]
> OpenAI / test (ubuntu-latest, 3.9) (pull_request) Successful in 61m


how much faster are the tests now, given that the latest run completed successfully in 61 minutes? @sonichi

**Comment by sonichi** [comment]
> > OpenAI / test (ubuntu-latest, 3.9) (pull_request) Successful in 61m
> 
> how much faster are the tests now, given that the latest run completed successfully in 61 minutes? @sonichi

reducing from 1h20m to <30m.

**Review by Hk669 — APPROVED** [review]
looks efficient, the changes do increase the test speed, as it is minimizing the iterations of the chat, keeping the config minimal with only `gpt-3.5-turbo`

**Comment by Hk669** [comment]
> > > OpenAI / test (ubuntu-latest, 3.9) (pull_request) Successful in 61m
> > 
> > 
> > how much faster are the tests now, given that the latest run completed successfully in 61 minutes? @sonichi
> 
> reducing from 1h20m to ~10m.

that's a great optimization.

**Pull request merged**
