### PR TITLE
Fix for runtime logging not supported with GPTAssistantAgent

### LINKED ISSUE #2498: [Bug]: Runtime logging not supported with GPTAssistantAgent
### Describe the bug

I followed the example mentioned in https://microsoft.github.io/autogen/docs/notebooks/agentchat_logging/
But when i replaced the AssistantAgent, with GPTAssistantAgent. The logs werent captured in the DB. No new entry added.

### Steps to reproduce

In the example https://microsoft.github.io/autogen/docs/notebooks/agentchat_logging/

just replace assistant with 

assistant = GPTAssistantAgent(
    name="assistant",
    llm_config=llm_config
)

and then try to get logs from sqlite, using steps given in same doc.

### Model Used

_No response_

### Expected Behavior

_No response_

### Screenshots and logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by pk673**
Please review  @IANTHEREAL @cheng-tan @jtrugman  @ekzhu  

## Why are these changes needed?

With this change we aim to support runtime-logging with GPTAssistantAgent 

## Related issue number

Closes #2498 
#2644

## Checks

- [ X] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ X] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by ekzhu** [comment]
@pk673 good that you started this. Can you work together with @krishnashed on this PR? I think he can submit a PR to your branch on your repo.

**Review by Hk669 — APPROVED** [review]
lgtm.

**Comment by krishnashed** [comment]
@Hk669 there is still some work left. I'll request for changes when needed

**Comment by Hk669** [comment]
> @Hk669 there is still some work left. I'll request for changes when needed

yeah sure. Thanks

**Comment by pk673** [comment]
@krishnashed Could you please elaborate on the changes that are still pending?

**Comment by krishnashed** [comment]
@pk673 can we connect? What's your discord username?

**Comment by Hk669** [comment]
> @pk673 can we connect? What's your discord username?

can you add me to the discussion? Thanks

**Comment by pk673** [comment]
@krishnashed @Hk669 My discord username is priyam_20775

**Comment by pk673** [comment]
@Hk669 Can you please let me know what changes are required?

**Review by krishnashed — APPROVED** [review]
@pk673 I tested your changes, they are good to be merged.

**Comment by ekzhu** [comment]
Can you also add me to the discord chat?

**Review by Hk669 — CHANGES_REQUESTED** [review]
@krishnashed i think this is only logging the last response of the group chat in chat completion log. is this issue solved?
@pk673 please look into the above issue

**Comment by Hk669** [comment]
> @krishnashed i think this is only logging the last response of the group chat in chat completion log. is this issue solved? @pk673 please look into the above issue

issue addressed in #2677

**Review by Hk669 — APPROVED** [review]
lgtm 👍

**Comment by Hk669** [comment]
@pk673 thanks for the contribution.

**Pull request merged**
