### PR TITLE
Support multimodal (GPT-4V) directly in OpenAIClient

### PR DESCRIPTION
**Pull request by BeibinLi**
This PR is part of the #1975 

As the [Major Update 1] in "Multimodal Orchestration", it enables the OpenAIClient to load images and to communicate with OpenAI directly. 

Hence, all ConversableAgent can use GPT-4V in the llm_config. The multimodal client will read the images before sending to OpenAI.

**RISK**: For dependencies issue and for avoiding circular import, we move "img_utils" from the contrib folder to the main autogen folder, which may cause errors. Workflow for testing is also updated. 

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [X] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by Josephrp — COMMENTED** [review]
very tidy so far, the explanation notebook is great for education too !

**Review by Josephrp — APPROVED** [review]

**Comment by afourney** [comment]
`is_multimodal_model` is a bit brittle IMHO. We should not be relying on the name alone for this (it already introduced a number of issues with Azure -- see #1682 for where it has bit us before. 

Ideally, this is a flag we should read from llm_config.

**Comment by BeibinLi** [comment]
@afourney

Good suggestion. I can add an optional parameter within llm_config.

**Comment by BeibinLi** [comment]
For automatic testing purpose, moving this PR from my folk to the upstream soon. See you there~

**Pull request closed without merging**
