### PR TITLE
Handle 400 context length errors

### LINKED ISSUE #1143: Streaming ONLY the final message?[Feature Request]:
### Is your feature request related to a problem? Please describe.

Hello.  I am using AutoGen as a retrieval augmented generation agent.  It works fantastically, and it performs multiple searches for different topics when necessary.  However, building and sending the final answer takes a long time, too long for my users.  I was hoping there is a way to stream just that one final answer, as it takes the majority of the time (Like 20 seconds out of 30 seconds total).  I looked at all the open issues and pull requests and I am still not sure of the status of streaming with AutoGen.

### Describe the solution you'd like

In the user_proxy agent class, have a parameter called stream_final_message = True.
This will allow all the agents to converse back and forth and pull whatever information is needed, but the final message is streamed so users don't have to wait for the entire formation of that message, because it tends to be long.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tylersuard**
Handle 400 context length errors before they happen by checking length of messages sent to OpenAI.  If length of messages exceeds context length, this function will loop through all the messages and cut each one down to the first 5,000 characters.

## Why are these changes needed?

I saw a TODO in this file for handling errors that occur when the context length is too long. https://github.com/microsoft/autogen/blob/a107233e23a8a08924919bccf732e3509f31939d/autogen/agentchat/conversable_agent.py#L624

## Related issue number
#858

### CODE REVIEW

**Comment by Tylersuard** [comment]
@microsoft-github-policy-service agree

**Comment by Tylersuard** [comment]
@sonichi I addressed the context length errors by truncating messages if the text sent to OpenAI is longer than the context length.  Context length is now an optional parameter that can be passed to ConversableAgent.

**Comment by sonichi** [comment]
There is a CompressibleAgent made by @kevin666aa which you may want to coordinate with.
#1143 doesn't exist.

**Comment by kevin666aa** [comment]
Hi @Tylersuard, can you checkout the compressible agent here? https://github.com/microsoft/autogen/blob/main/notebook/agentchat_compression.ipynb 
https://github.com/microsoft/autogen/blob/main/autogen/agentchat/contrib/compressible_agent.py
This is supposed to be an approximate of conversable_agent but would check for tokens before calling LLM services.

If you would like to contribute a new way of handling messages, it is quite easy to do so in line 248 of `contrib/compressible_agent.py`. Let me know if you have any questions.

**Pull request closed without merging**
