### PR TITLE
add xai model client

### PR DESCRIPTION
**Pull request by me020523**
## Why are these changes needed?

enable autogen to support XAI models

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by me020523** [comment]
@microsoft-github-policy-service agree [company="me020523"]

**Comment by me020523** [comment]
@microsoft-github-policy-service agree

**Review by ekzhu — CHANGES_REQUESTED** [review]
Thanks for the PR. Generally, for model clients we encourage you to create and maintain a community Pypi package, and we can index them in our documentation. 

See: https://microsoft.github.io/autogen/dev/user-guide/extensions-user-guide/index.html

**Comment by me020523** [comment]
Thank you for your response and suggestion.

**Comment by ekzhu** [comment]
@me020523  you can update this PR to include an entry that points to your package once you have created it.

**Pull request closed without merging**
