### PR TITLE
bump version to 0.2.1

### LINKED ISSUE #866: Request for new release version of AutoGen with AgentBuilder included??
Background: 

While going through the tutorial, we noticed that AgentBuilder was merged in 18 hours ago.
https://microsoft.github.io/autogen/blog/2023/11/26/Agent-AutoBuild

Thank you!

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

For new release. Limit openai version before #791 solves the breaking change caused by openai v1.3.

## Related issue number

close #866

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by JieyuZ2** [comment]
we should merge #865 first?

**Review by rlam3 — APPROVED** [review]
looks good to me :) ! thank you!

**Comment by sonichi** [comment]
> we should merge #865 first?

Sure. Let @qingyun-wu know when it's ready.

**Review by gagb — APPROVED** [review]

**Review by JieyuZ2 — APPROVED** [review]

**Comment by qingyun-wu** [comment]
@BeibinLi  could you take a look at the test error from group chat? https://github.com/microsoft/autogen/actions/runs/7105967042/job/19344368764?pr=867#step:8:2 The error is associated with the `content_str` func. Thank you!

**Comment by kevin666aa** [comment]
https://github.com/microsoft/autogen/pull/791#issuecomment-1841130216
@BeibinLi Maybe we should limit the version to less than 1.1.0.

**Review by qingyun-wu — APPROVED** [review]

**Pull request merged**
