### PR TITLE
Icons not centered in the "autogen_agentchat.png"

### PR DESCRIPTION
**Pull request by Steellgold**
## Why are these changes needed?

I've centered the icons

### CODE REVIEW

**Comment by qingyun-wu** [comment]
Thanks for the contribution, but I do not see any difference after deploying the website with the updated fig locally? Can you double-check the change?

**Comment by Steellgold** [comment]
Hmm, I think it's because you are displaying directly from the link and not the directory file

**Comment by sonichi** [comment]
The difference is in the location of the three icons in the leftmost figure.

**Comment by Steellgold** [comment]
@qingyun-wu 

Default (https://github.com/microsoft/autogen/blob/main/website/static/img/autogen_agentchat.png)

image

My PR (https://github.com/SteellgoldStock/autogen/blob/main/website/static/img/autogen_agentchat.png

image

**Review by qingyun-wu — APPROVED** [review]
Thanks!

**Pull request merged**
