### PR TITLE
Create OAI_CONFIG_LIST

### PR DESCRIPTION
**Pull request by thegreatestcompany**
## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by gagb** [comment]
Can you please specify why are these changes necessary? There is a sample config in the root.

**Comment by BeibinLi** [comment]
Are we going to use "base_url" instead of "api_base" here?

If yes, should we wait #383 first?

**Comment by gagb** [comment]
> Are we going to use "base_url" instead of "api_base" here?
> 
> If yes, should we wait #383 first?

This PR is adding a new file to the notebooks folder. I still see it using `api_base`

**Comment by sonichi** [comment]
#383 and all the subtasks for #203 are merged to the dev/v0.2 branch. We won't merge #393 to main until all the subtasks are solved.

**Review by AaronWard — CHANGES_REQUESTED** [review]
Not quite sure what the purpose of this PR is

**Comment by gagb** [comment]
I think this PR is not necessary given the instruction number 2 in https://github.com/microsoft/autogen#quickstart

**Comment by AaronWard** [comment]
@gagb @thegreatestcompany Seeing as there is no response i will go ahead and close this PR

**Pull request closed without merging**
