### PR TITLE
Support for Human Input Mode in AutoGen Studio

### PR DESCRIPTION
**Pull request by victordibia**
Add support for human input mode implemented by @SailorJoe6 in PR #3476 

The AutoGenStudio UI doesn't currently support user input modes 'ALWAYS', or 'TERMINATE' which are vital when allowing agents to generate and run code, so that the user can verify the code before it gets execute in their environment. This is likely due to difficulties encountered with Python's asyncio event loop getting blocked by synchronous calls to the AutoGen chat functions. This PR fixes those issues and adds support for all human input modes:

This code comes in multiple commits so you can follow the logical progression through:
1) Update the AutoGenStudio to use async through the entire call stack
2) Leverage the async nature to make adding human input much eassier

 

## Related issue number

Resolves https://github.com/microsoft/autogen/issues/1358
Resolves https://github.com/microsoft/autogen/issues/1664
Part of roadmap https://github.com/microsoft/autogen/issues/737

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by gagb — COMMENTED** [review]
image
When I do yarn build in Codespace with the studio devcontainer I get the following error. The error happens with both python 3.10 and 3.11.

**Comment by victordibia** [comment]
> image When I do yarn build in Codespace with the studio devcontainer I get the following error. The error happens with both python 3.10 and 3.11.

The message above indicates you might not have checked out some image files correctly - specifically `[frontend/src/images/icon.png](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/frontend/src/images/icon.png)` file. Any chance you can verify if that file is corrupted for you, delete it and replace it with a new version from [here](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/frontend/src/images/icon.png)?

**Review by gagb — APPROVED** [review]
Thank you @victordibia and @SailorJoe6 -- fantastic PR and sorry for the delay. I was away for the weekend.

@victordibia's suggestion to manually checkout the `icon.png` fixed the issue I was getting with `yarn build`. Is there a more permanent fix for this -- it will affect anyone who uses Codespaces for development?

I was able to run the UI to create a simple ChatGPT where the user proxy is in `human_input_mode=ALWAYS` and it worked.

There are some small design decisions that I found confusing, in particular:
1. The request for user input is posted as another message to the chat history in the UI . 
2. The spinning wheel that indicates agents are working continues to spin the exact same way while waiting for user input.

I think a different visual identity for both of these could reduce confusion. Choice 2 in particular made me think multiple times that I was waiting for system response. For choice 1, maybe we can change the color (if possible)?

**Comment by victordibia** [comment]
I agree with the feedback @gagb , perhaps we can open and track in a separate repo. 
Will merge this in in the mean time.

**Comment by gagb** [comment]
> I agree with the feedback @gagb , perhaps we can open and track in a separate repo. 
> 
> Will merge this in in the mean time.

Sounds great!

**Comment by SailorJoe6** [comment]
Thanks for considering my PR!  Excellent feedback.  Re: comment 1) I agree.  My first attempt relied only on the Info toast-message, but I found I overlooked it too many times.  Adding the prompt as the "default message" in the input textarea was probably enough, and it's super easy to just ignore it rather than post it as another message.  In the end, I'm not very usefule as a UI designer and much better at implementing the ideas ;-).  

Anyway, I'll be following the conversation.  AutoGenStudio is just awesome!   Excellent work on this!

**Comment by gagb** [comment]
@jackgerrits, can we please enable adding @SailorJoe6 as a reviewer to this project? :)

**Pull request merged**
