### PR TITLE
Remove system message functionality from code executors

### PR DESCRIPTION
**Pull request by jackgerrits**
## Why are these changes needed?

@ekzhu as discussed this removes all system message functionality. We agreed that this should be solved a different way, starting with documenting how to create good system messages. Doing this now before code executors become too mature.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by ekzhu** [comment]
More context: We are still thinking about a proper approach to solve the compatibility contract that binds the code executor and code writer agents together. Before we have a good design, it was pre-mature to use system message instruction update. Thus, the proposal to remove it. Note: this feature has not been documented anywhere or recommended to use since released. Since many have reviewed it, need to get feedback on whether removing it is going to cause massive downstream rewrites. 

Alternatively, we can keep the feature there, but insert explicit warning on possible removal/changes.

**Comment by rickyloynd-microsoft** [comment]
> @rickyloynd-microsoft @IANTHEREAL since you were in the discussion earlier regarding the user capability, what's your comment on this? Jack and mine rational is that we are not sure if capability is the right abstraction to perform this system message update, so we want to avoid over-engineer this. The current capability only performs a system message update, which is brittle.

Yes, I agree that introducing a `UserCapability` mechanism (similar to the `AgentCapability` mechanism) would be overkill for simply updating a system message. Maybe there would be a stronger case for such a mechanism in the future, but I'm a fan of waiting until a feature is actually needed before doing much work to implement it.

**Comment by IANTHEREAL** [comment]
> @rickyloynd-microsoft @IANTHEREAL since you were in the discussion earlier regarding the user capability, what's your comment on this? Jack and mine rational is that we are not sure if capability is the right abstraction to perform this system message update, so we want to avoid over-engineer this. The current capability only performs a system message update, which is brittle.

I have no objections to first removing it. Moreover, I believe conducting more tests on placing the code executor guide in various structured prompts is essential. Such experiments would yield valuable insights for optimizing our approach.

**Review by ekzhu — DISMISSED** [review]

**Comment by ekzhu** [comment]
Thanks @rickyloynd-microsoft and @IANTHEREAL. I made the PR ready for review.

**Review by jackgerrits — COMMENTED** [review]
Thanks for the updates @ekzhu!

**Comment by IANTHEREAL** [comment]
Just one question - Will the code executor work well after this PR merged, or will it affect our developers?

**Review by rickyloynd-microsoft — APPROVED** [review]

**Review by IANTHEREAL — APPROVED** [review]

**Comment by sonichi** [comment]
Could you make the PR from the upstream to run the openai test?

**Comment by jackgerrits** [comment]
See PR: #1933

**Pull request closed without merging**
