### PR TITLE
Update graph_utils.py

### PR DESCRIPTION
**Pull request by moresearch**
Adds export_path for visualize_speaker_transitions_dict

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by joshkyh — CHANGES_REQUESTED** [review]
Thanks for coming back with a PR.

Given the 90+% overlap with `visualize_speaker_transitions_dict`, I'd suggest adding a export_path:str which defaults to None into `visualize_speaker_transitions_dict`. In there, run plt.savefig(path) if `export_path` is not None

**Review by joshkyh — APPROVED** [review]
Thank you @moresearch. Looks good to me! :)

**Comment by joshkyh** [comment]
Hey @moresearch, a tip to run `pre-commit run --all-files` on the root folder of the Autogen dev container to pass
Code formatting / pre-commit-check (pull_request) Failing after 41s

**Comment by moresearch** [comment]
Thanks for the tip @joshkyh

**Review by joshkyh — APPROVED** [review]
Looks good to me, and non-llm tests are passing. Perhaps good to merge, @ekzhu?

**Pull request merged**
