### PR TITLE
Fix broken relative links

### PR DESCRIPTION
**Pull request by jonrichards**
## Why are these changes needed?

Fixes broken urls that were already relative to the `docs` folder.

### Example

Original url: https://microsoft.github.io/autogen/docs/docs/notebooks/agentchat_nested_chats_chess

Fixed url: https://microsoft.github.io/autogen/docs/notebooks/agentchat_nested_chats_chess

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by jonrichards** [comment]
I didn't see https://github.com/microsoft/autogen/pull/2664 before I submitted this, but there were other broken links fixed here than that PR fixed.

**Comment by sonichi** [comment]
As mentioned in #2664 , this fix won't always work. It fixes one situation but introduces broken links in another.

**Comment by jonrichards** [comment]
> As mentioned in #2664 , this fix won't always work. It fixes one situation but introduces broken links in another.

If I'm understanding that correctly, you're saying https://microsoft.github.io/autogen/docs/tutorial/tool-use/#summary does not exhibit the behavior? Because they do not work for me from that link.

**Comment by sonichi** [comment]
> > As mentioned in #2664 , this fix won't always work. It fixes one situation but introduces broken links in another.
> 
> If I'm understanding that correctly, you're saying https://microsoft.github.io/autogen/docs/tutorial/tool-use/#summary does not exhibit the behavior? Because they do not work for me from that link.

I don't know exactly what triggers an extra "/docs" to be inserted and what doesn't. Even for the same link, it works in some situations and fails in others. You can also find the CI failure in https://github.com/microsoft/autogen/actions/runs/9239749934/job/25419277568?pr=2794

**Comment by jackgerrits** [comment]
Closing, docusaurus links are handled weirdly. This should be fixed in later changes

**Pull request closed without merging**
