### PR TITLE
api_base -> base_url

### LINKED ISSUE #384: openai.api_base -> openai.base_url

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

openai package change

## Related issue number

#203
close #384

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by Gourav2609 — APPROVED** [review]
LGTM

**Review by gagb — APPROVED** [review]

**Review by olaoluwasalami — APPROVED** [review]

**Review by AaronWard — APPROVED** [review]
I scoured the repo to see any other occurrences of `api_base` being used and looks good on my end 👍

**Review by 05hiteshbansal — APPROVED** [review]

**Comment by masterujjval** [comment]
Looks great 👍

**Review by priyansh4320 — COMMENTED** [review]
okay great

**Pull request merged**
