### PR TITLE
add a verbose flag to let gpt assistant print more log

### PR DESCRIPTION
**Pull request by IANTHEREAL**
## Why are these changes needed?

Let GPT Assistant be able to print input/output of function call using a verbose flag

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by rickyloynd-microsoft** [comment]
@gagb fyi

**Review by thatbreezeofmine — APPROVED** [review]

**Comment by sonichi** [comment]
Looks good. Please make sure @kevin666aa approves before merging.

**Comment by gagb** [comment]
@IANTHEREAL should we first get this merged and base this on it? https://github.com/microsoft/autogen/pull/665/files I worry that there are some overlaps -- it also added `kwargs` and added some additional logging.

**Comment by IANTHEREAL** [comment]
> @IANTHEREAL should we first get this merged and base this on it? https://github.com/microsoft/autogen/pull/665/files I worry that there are some overlaps -- it also added `kwargs` and added some additional logging.

@gagb no problem

**Comment by IANTHEREAL** [comment]
The user seems more urgent about this PR request: https://github.com/microsoft/autogen/issues/715

I borrowed the kwargs parameter from https://github.com/microsoft/autogen/pull/665, keeping the necessary parameters simple. Additionally, compared to logging output, I prefer to use a unified format in the ConversableAgent to output complete function execution information when needed by the user. This kind of output is more understandable and convenient for tracking. @gagb @sonichi @kevin666aa PTAL

**Review by kevin666aa — APPROVED** [review]

**Pull request merged**
