### PR TITLE
AutoGen meets SWE_bench

### PR DESCRIPTION
**Pull request by skzhang1**
## Why are these changes needed?

This PR provides a basic implementation for SWE_bench benchmark (https://www.swebench.com). This PR is still on working and not ready for review. 

- [ ] Specific packages pre-requirement
- [ ] Documentations (notebook, blogpost)
- [ ] Clean the codes. 

🌹 Acknowledgement: The code is greatly on the basis of swe-agent. 

Please add more @Hk669 if you have other suggestions.  @Hk669 will mainly take response for it based on this draft PR. 

## Related issue number

N/A

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by ekzhu** [comment]
@skzhang1 would you like to continue working on this draft PR?

**Comment by skzhang1** [comment]
@ekzhu Hi, I may not working on it recently. This PR provides a basic implementation and it is workable. I hope other people in the community could further work on it based on this PR. @Hk669

**Comment by ekzhu** [comment]
Thanks. Do you think we can close this and revisit the idea once the new version is merged? It can be part of `agbench`

**Comment by Hk669** [comment]
> Thanks. Do you think we can close this and revisit the idea once the new version is merged? It can be part of `agbench`

Sure @ekzhu , we can revisit after the new version. `agbench`

**Pull request closed without merging**
