### PR TITLE
Add Couchbase VectorDB Support

### PR DESCRIPTION
**Pull request by lokesh-couchbase**
## Why are these changes needed?
Couchbase is a NoSQL Key-Value Based Database. Couchbase has recently added support for Vector Search. We would like to add support for Couchbase as a vectorDB in autogen.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by lokesh-couchbase** [comment]
@microsoft-github-policy-service agree company="Couchbase"

**Review by jackgerrits — APPROVED** [review]
Thanks!

**Comment by lokesh-couchbase** [comment]
HI @jackgerrits , I have fixed the formatting issues
Thanks

**Comment by jackgerrits** [comment]
Thank you!

**Review by jackgerrits — APPROVED** [review]

**Pull request merged**
