### PR TITLE
Add Chinese translation for README

### PR DESCRIPTION
**Pull request by zerd1y**
## Why are these changes needed?As a new undergraduate student in China, I know that many students can not directly and easily understand the project because of the language. This can make the project provide a better reading experience, help the project spread, and expand the impact of the project.

Chinese translation for README

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by zerd1y** [comment]
@microsoft-github-policy-service agree [company="{your company}"]
@microsoft-github-policy-service agree

**Comment by zerd1y** [comment]
@microsoft-github-policy-service agree

**Comment by zerd1y** [comment]
@microsoft-github-policy-service agre

microsoft-github-policy-service[bot] ***@***.***> 于
2024年10月6日周日 下午2:27写道：

**Comment by zerd1y** [comment]
@microsoft-github-policy-service agree

Jinghuai Xiao ***@***.***> 于 2024年10月6日周日 下午7:23写道：

**Comment by ekzhu** [comment]
If you are interested in working on  a complete translation for the autogen documentation, consider creating a separate GitHub repository to host it. If it's just the readme file, there are many LLMs can translate reasonably well. Consider closing this PR first and start a discussion thread for this topic. Thanks!

**Pull request closed without merging**
