### PR TITLE
Fix for displaying videos on AutoGen Studio

### PR DESCRIPTION
**Pull request by brotsky**
## Why are these changes needed?

This fixes a problem I noticed when generating MP4 videos. The video's file type is unknown in its metadata so I used the file extension instead. 

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by brotsky** [comment]
This was the problem:
Screenshot 2023-12-27 at 11 19 49 PM

And this is with my solution:
Screenshot 2023-12-27 at 11 19 06 PM

**Comment by rysweet** [comment]
This PR is against AutoGen 0.2. AutoGen 0.2 has been moved to the 0.2 branch. Please rebase your PR on the 0.2 branch or update it to work with the new AutoGen 0.4 that is now in main.

**Comment by victordibia** [comment]
Closing this as stale for now.

**Comment by rysweet** [comment]
actually closing it

**Pull request closed without merging**
