### PR TITLE
Fix custom client registration

### PR DESCRIPTION
**Pull request by olgavrou**
## Why are these changes needed?

For custom client registration:

- Removing redundant check for placeholder config inside config list
- configs in `self._config_list` can end up having the extra `kwargs` passed through (e.g. `cache_seed`) and therefore the check for `placeholder_config` in `self._config_list` will fail

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by ekzhu — APPROVED** [review]
Can we add a test just to make sure additional config arguments like `cache_seed` won't trigger an error? 

Also in `test_custom_client.py` (basically all other tests as well, but we don't have to do everything in this PR) we don't need to check for `openai` package existence as it is a required dependency.

**Review by ekzhu — CHANGES_REQUESTED** [review]
Can we add a test just to make sure additional config arguments like `cache_seed` won't trigger an error? 

Also in `test_custom_client.py` (basically all other tests as well, but we don't have to do everything in this PR) we don't need to check for `openai` package existence as it is a required dependency.

**Comment by olgavrou** [comment]
> Can we add a test just to make sure additional config arguments like `cache_seed` won't trigger an error?
> 
> Also in `test_custom_client.py` (basically all other tests as well, but we don't have to do everything in this PR) we don't need to check for `openai` package existence as it is a required dependency.

@ekzhu good point, added unit test, checked that it failed with old code, and passes with PR changes. Also removed the openai req

**Comment by ekzhu** [comment]
Remember to check the code in #1667 also to see if it works with this update. It works on my side.

**Review by ekzhu — APPROVED** [review]

**Pull request merged**
