### PR TITLE
document about docker

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

Recommend using docker for code execution.

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by pcdeadeasy — COMMENTED** [review]
Changes look good. Do you think we need to write about the DevContainer option?

**Review by afourney — COMMENTED** [review]
Looks reasonable. I would recommend the following two changes:

**README.md**
For code execution, we strongly recommend using docker. ->
For code execution, we strongly recommend installing the python docker package, and using Docker.

**conversible_agents.py**
Default is True when the docker package is installed, which will be converted into a list. We strongly recommend using docker for code execution.
->
Default is True when the docker python package is installed, but is otherwise False. We strongly recommend using docker for code execution.

Further I don't understand what you mean by "which will be converted into a list". Perhaps something like the following would be better: "When set to True, an appropriate Docker image will be selected from a default list."

**Comment by sonichi** [comment]
> When set to True, an appropriate Docker image will be selected from a default list.

It's already written. "running autogen in a docker container" means it. DevContainer is a special case of a docker container.

**Comment by pcdeadeasy** [comment]
> > When set to True, an appropriate Docker image will be selected from a default list.
> 
> It's already written. "running autogen in a docker container" means it. DevContainer is a special case of a docker container.

It will help to make that explicit in my opinion but everything else looks good.

**Review by pcdeadeasy — APPROVED** [review]

**Pull request merged**
