### PR TITLE
Update notebook format

### PR DESCRIPTION
**Pull request by qingyun-wu**
## Why are these changes needed?

Update notebook format for better webpage display. 

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by jackgerrits — APPROVED** [review]

**Comment by qingyun-wu** [comment]
Note: @jackgerrits will help fix the doc format error. Thank you Jack!

**Comment by ekzhu** [comment]
Forgot to check in image?

**Comment by sonichi** [comment]
> Note: @jackgerrits will help fix the doc format error. Thank you Jack!

Thanks @jackgerrits and @qingyun-wu

**Comment by jackgerrits** [comment]
@qingyun-wu fixed now

**Pull request closed without merging**
