### PR TITLE
Human Input Mode: update input prompt message to include responding agent's agent name

### PR DESCRIPTION
**Pull request by jatins**
## Why are these changes needed?
Currently the input prompt only mentioned who agent is replying to. However, I was often confused _who_ was replying. 

**This PR** 
* After this change the input prompt also mentions who you are replying _as_ (i.e. the responding agent) in the input prompt.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by jatins** [comment]
@microsoft-github-policy-service agree

**Review by RohitRathore1 — APPROVED** [review]
LGTM

**Comment by jatins** [comment]
@RohitRathore1 @sonichi thanks for review! Is this good to be merged? Just checking if this needs any further action from my end.

**Review by qingyun-wu — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
