### PR TITLE
Fix #2845 - LocalCommandLineCodeExecutor is not working with virtual environments

### LINKED ISSUE #2845: [Bug]: LocalCommandLineCodeExecutor is not working with virtual environments
### Describe the bug

I am trying to run a simple hello word script using LocalCommandLineCodeExecutor. I always get the "The system cannot find the path specified." output.

So, I explored the source code for a while and found that the command sent to the subprocess was wrong.
instead of absolute path, relative path of virtual env is used to activate. So, when the control is already inside "coding" directory. it sends commands like this `coding\\.venv\\Scripts\\activate.bat && python E:\\Workspace\\AI Training\\AI Agents\\AutoGenExamples\\coding\\tmp_code_7f9e869133ec86dd8316e6610419e87e.py`

One more thing to note here - The python path contains spaces in folder names. there is no surrounding quotes.

Run Below code to reproduce the issue.

### Steps to reproduce

from autogen.code_utils import create_virtual_env
from autogen import ConversableAgent
from autogen.coding import LocalCommandLineCodeExecutor

venv_dir = ".venv"
venv_context = create_virtual_env(venv_dir)

executor = LocalCommandLineCodeExecutor(
    timeout=10,  # Timeout for each code execution in seconds.
    work_dir="coding",  # Use the temporary directory to store the code files.
    virtual_env_context=venv_context,
)

code_executor_agent = ConversableAgent(
    "code_executor_agent",
    llm_config=False,  # Turn off LLM for this agent.
    code_execution_config={
        "executor": executor
    },  # Use the local command line code executor.
    human_input_mode="NEVER",  # Always take human input for this agent for safety.
    max_consecutive_auto_reply=1,  # Only allow one auto-reply for this agent.
)

message_with_code_block = """This is a message with code block.

The code block is below:
```python
print("Hello, World!")
```
This is the end of the message.
"""

reply = code_executor_agent.generate_reply(
    messages=[{"role": "user", "content": message_with_code_block}]
)
print(reply)

### Model Used

N/A

### Expected Behavior

I should see an output "Hello, World!"

### Screenshots and logs

Error:
image

Debug Output:
image

### Additional Information

image

### PR DESCRIPTION
**Pull request by NanthagopalEswaran**
## Why are these changes needed?

When the virtual env path is relative, local code executer fails to execute any code blocks.

Fix proposed: Finding the absolute path of bin folder and use it going forward.

Note: absolute path finding happens through os module so the fix should work in all os.

## Related issue number

"Closes https://github.com/microsoft/autogen/issues/2845"

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by qingyun-wu** [comment]
@NanthagopalEswaran, thanks for the PR! Could you fix code format issues? You can run pre-commit to help with it.

**Comment by Deykeepcomn4me** [comment]
These are hackers hacking me please contact fbi

**Comment by NanthagopalEswaran** [comment]
> @NanthagopalEswaran, thanks for the PR! Could you fix code format issues? You can run pre-commit to help with it.

Thanks @qingyun-wu. I fixed the issues in my code. I ran `pre-commit run --all-files` and didn't get any formatting issues now. Please try the checks now.

**Review by Gr3atWh173 — APPROVED** [review]

**Review by thinkall — APPROVED** [review]
Thank you @NanthagopalEswaran ! Looks good to me.

**Pull request merged**
