### PR TITLE
fix(path): Update Installation.md -Update Dockerfile path for Autogen base image build

### PR DESCRIPTION
**Pull request by samuelogboye**
This pull request addresses an issue with the Docker build command in the documentation. The original command:

`docker build -f .devcontainer/base/Dockerfile -t autogen_base_img https://github.com/microsoft/autogen.git
`
was updated to:

`docker build -f .devcontainer/Dockerfile -t autogen_base_img https://github.com/microsoft/autogen.git
`
The change eliminates the need to specify "base" in the Dockerfile path when building base images. This adjustment ensures consistency and aligns with the correct path structure.

**Reason for the Change:**

The previous command had an unnecessary "base" in the Dockerfile path, causing confusion and inconsistency. The updated command simplifies the path, making it more intuitive for users to build base images.

**Testing:**

The updated command has been tested locally to confirm that it successfully builds the Autogen base image. The build process completes without errors, and the resulting image is as expected.

Error with the former path
image

## Checks

- [ x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by samuelogboye** [comment]
@sonichi

**Comment by samuelogboye** [comment]
@sonichi 
@gagb 
@victordibia 

kindly check this out.

thanks

**Comment by sonichi** [comment]
@samuelogboye Sorry that I didn't review this earlier. #1533 fixes the same problem, but if you could fix the conflict within the next 24 hours, I would merge your PR first.

**Comment by olaoluwasalami** [comment]
Hello @samuelogboye Please fix conflicts, and I'll approve

**Comment by samuelogboye** [comment]
> @samuelogboye please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by olaoluwasalami — APPROVED** [review]
LGTM!

**Pull request merged**
