### PR TITLE
docs: initial Jupyter support for website docs, move config notebook

### PR DESCRIPTION
**Pull request by jackgerrits**
Adds initial support for rendering notebooks using [`Quarto`](https://quarto.org/). Quarto is a tool for rendering technical documentation. It has specific support for rendering Jupyter notebooks that target the Docsaurus documentation system so it is particularly helpful for us.

Additionally, in this PR I moved the oai_openai_utils notebooks to the main docs section as it is a great notebook for explaining how to setup the LLM config list. I made a small edit to add a `TL;DR` section at the top of the notebook to get started quickly.

Sidebar with new page:
image

Example of rendered notebook:
image

## Related issue number

#1339

### CODE REVIEW

**Review by ekzhu — CHANGES_REQUESTED** [review]
Looks great. One thing I would consider doing is having test in place for the notebooks we have in documentation.

**Comment by jackgerrits** [comment]
Agreed - @zwd-ms has taken on that task and will be done separately to this PR.

**Comment by ekzhu** [comment]
> Agreed - @zwd-ms has taken on that task and will be done separately to this PR to ensure it is a holistic solution.

Thanks @zwd-ms!

**Comment by sonichi** [comment]
Shall we move it under "Installation"? I think order wise, it's after installation and before use cases.

**Comment by jackgerrits** [comment]
> Shall we move it under "Installation"? I think order wise, it's after installation and before use cases.

I agree, moved it.

**Pull request merged**
