### PR TITLE
Enable human interaction in AutoGenStudio

### LINKED ISSUE #1358: [Feature Request]:   Autogen Studio unable to change human input mode
### Describe the bug

When I spin up autogen studio and try to create a new agent, I can't change the human input mode from NEVER to anything else.  There is no other selection.  This is with all agents including user proxy agents.

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### Screenshots and logs

_No response_

### Additional Information

_No response_

### LINKED ISSUE #1664: [Issue]: Autogen Studio UI 2.0  Human Input Mode
### Describe the issue

Hi, I'm using Autogen Studio UI 2.0.

I'm creating an Agent which requires Human Input, when I use the Autgen UI studio to create an agent -> I cannot see any options other than 'NEVER' in the Human Input Field.

Kindly Help me with the same and how can i overcome this situation of having Human Input to 'YES' in UI

Installation Process I followed https://microsoft.github.io/autogen/blog/2023/12/01/AutoGenStudio/

Screenshot 2024-02-13 at 13 06 22

### Steps to reproduce

_No response_

### Screenshots and logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SailorJoe6**
## Why are these changes needed?

The AutoGenStudio UI doesn't currently support user input modes 'ALWAYS', or 'TERMINATE' which are vital when allowing agents to generate and run code, so that the user can verify the code before it gets execute in their environment.  This is likely due to difficulties encountered with Python's asyncio event loop getting blocked by synchronous calls to the AutoGen chat functions.  This PR fixes those issues and adds support for all human input modes

## Related issue number

Resolves #1358
Resolves #1664 
Part of roadmap #737 

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by SailorJoe6** [comment]
@microsoft-github-policy-service agree

**Comment by victordibia** [comment]
hi @SailorJoe6 ,

Thanks for this PR. I tested it and it works mostly - really well done! I am eager to merge this in!
I recently updated the `autogenstudio` branch, rebasing on main hence the inconsistencies above. 
Can you kindly help with the following.

- Recreate your  [PR](https://github.com/SailorJoe6/autogen/commit/b4c5603f6a7d6e02c31dac56f0690308e16cac7f) based on current autogenstudio  
- The [asyncio logic in websocketmanger](https://github.com/SailorJoe6/autogen/blob/b4c5603f6a7d6e02c31dac56f0690308e16cac7f/samples/apps/autogen-studio/autogenstudio/web/websocketmanager.py#L77). (`asyncio.timeout`) seems to depend on pythong 3.11. Any chance this can be rewritten to function in python 3.10?

**Comment by SailorJoe6** [comment]
Hey @victordibia Thanks for the review.  I'm happy to re-submit based off the most recent main.   Should I submit a PR to merge this to main then?

**Comment by SailorJoe6** [comment]
Almost forgot.  I'm sure I can re-write the Asyncio timeout logic to work in 3.10

**Comment by SailorJoe6** [comment]
Ask and you shall receive ;-)
#3445

**Pull request closed without merging**
