### PR TITLE
Create a MongoDB retrieval Agent

### PR DESCRIPTION
**Pull request by cozypet**
### Using RetrieveChat with MongoDB for Retrieve Augmented Code Generation and Question Answering

MongoDB has been ranked as the best vector database(https://www.mongodb.com/blog/post/atlas-vector-search-commands-highest-developer-nps-retool-state-ai-2023-survey) in the Retool AI report, so it is quite important to add MongoDB vector search as an option for Autogen RAG.

You can easily start the MongoDB vector search on a free tier M0 MongoDB Atlas cluster. Free tier cluster provides the full functionality of the MongoDB vector search.  https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-overview/

### But why is MongoDB such a standout? Well, there are a few key reasons.

 1. MongoDB Atlas integrates smoothly with existing databases. For organizations already using MongoDB, this means a seamless expansion into the vector storage—no major system overhauls required!
 2. MongoDB Atlas is built to handle operational heavy-lifting. It excels when serving large-scale, mission-critical applications, offering robustness and reliability where it counts.
 3. MongoDB's flexibility in handling a variety of data types and structures makes it perfectly suited to the complexity of vector embeddings.

As such, implementing MongoDB as a Retrieval Agent can unlock new potential in your AI applications, bringing the full power of vector storage to bear.

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by cozypet** [comment]
@microsoft-github-policy-service agree [company="{}"]

**Comment by cozypet** [comment]
@microsoft-github-policy-service agree

**Comment by thinkall** [comment]
@cozypet Thank you very much for your contribution! Could you please also add tests and an example notebook for it? You can take #303 as an example.

**Comment by cozypet** [comment]
I can run successfully the test file locally, but not be able to pass the build phase.

**Review by thinkall — COMMENTED** [review]
https://microsoft.github.io/autogen/docs/Contribute/#pre-commit

@cozypet this doc would save your time on formatting

**Comment by AyushExel** [comment]
I guess this should work but there could be an alternative approach to implement it as by simply using the interface provided by #619

**Comment by thinkall** [comment]
Since there is no vector searching in oss mongodb yet. Maybe a notebook is better for demonstrating mongodb integration. WDYT @sonichi ?

**Comment by cozypet** [comment]
> Since there is no vector searching in oss mongodb yet. Maybe a notebook is better for demonstrating mongodb integration. WDYT @sonichi ?

Added a notebook as requested, please help to review.

**Comment by sonichi** [comment]
@thinkall could you advise how to write the test to avoid the build error?

**Comment by ranfysvalle02** [comment]
@sonichi @thinkall @cozypet -

I think the issue here is -- MongoDB Atlas search is 'cloud only' and cannot be run in a in the Docker environment like we do with Postgres.



`.github>workflows>contrib-openai.yaml` **ankane/pgvector**

Screenshot 2024-05-23 at 9 30 52 PM


Any suggested path forward here?

**Comment by thinkall** [comment]
> @sonichi @thinkall @cozypet -
> 
> I think the issue here is -- MongoDB Atlas search is 'cloud only' and cannot be run in a in the Docker environment like we do with Postgres.
> 
> `.github>workflows>contrib-openai.yaml` **ankane/pgvector**
> 
> Screenshot 2024-05-23 at 9 30 52 PM
> Any suggested path forward here?

Hi @ranfysvalle02 , we have new abstract of vectordb https://github.com/microsoft/autogen/tree/main/autogen/agentchat/contrib/vectordb . I would suggest add a new mongodb class. No new agent is needed. Would you like to work on it?

**Comment by ranfysvalle02** [comment]
@thinkall 

Here is the Pull Request: https://github.com/microsoft/autogen/pull/2942

**Comment by Deykeepcomn4me** [comment]
These are hackers hacking me please contact fbi

**Pull request closed without merging**
