### PR TITLE
print exit feedback for user

### LINKED ISSUE #706: GroupChat: Feedback to the user when it finishes early
With GroupChat, if max_rounds is reached Autogen will just stop, with no feedback to the User. 

It would be very useful to have some feedback, such as a message to say why it's stopped. 

There may be other instances when it stops with no feedback, such as reply returning None or a function returning None.

### PR DESCRIPTION
**Pull request by PyroGenesis**
## Why are these changes needed?

This would help inform the user when a conversation has ended and for what reason.

## Related issue number

Closes #706

### One-to-one conversation - agent returns termination msg
image

### One-to-one conversation - agent returns None
image

### One-to-one conversation - max consecutive auto-reply limit
image

### One-to-one conversation - terminated by human
image

### GroupChat conversation - agent returns termination msg
image

### GroupChat conversation - agent returns None
image

### GroupChat conversation - max rounds limit
image

### GroupChat conversation - terminated by human
image

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by PyroGenesis** [comment]
@microsoft-github-policy-service agree company="Personable Inc."

**Comment by PyroGenesis** [comment]
Is this a good way to implement this? 

Another possible way I was thinking of was to have the exit reason propagate from the last agent. through the `send` / `receive` calls, back to the agent who initiated the conversation which would then print the exit reason. However, that would lead to changes in the `send` / `receive` method signatures of `ConversableAgent` (and `Agent`).

**Comment by sonichi** [comment]
I think the termination reason message is only necessary when the termination is not triggered by a human input. But I'm not a HCI expert. So trying to get help from @afourney @gagb

**Comment by afourney** [comment]
This is an interesting PR. I think if we are providing the feedback for the benefit of the user/developer, then we don't necessarily need the manual termination message. BUT if we want to use this signal to manage any other automation, we likely do want it.

That is a good segue to my question: Is there simple way of adding a programmatic means of accessing this signal? E.g., can I subscribe to it somehow? Or, can I read from some status variable? I think this would be very useful for some orchestration scenarios.

**Comment by jtoy** [comment]
@afourney I love the idea of having having signals or hooks to be able to subscribe to events, it would definitely make for a more powerful and robust system.

**Comment by PyroGenesis** [comment]
I see that there is an implementation of adding Termination reason to the chat history for groupchat in the `experimental` branch. That seems like a better approach and would satisfy the idea of programmatically processing the termination reason. Is that approach planned to be merged into the main branch for conversable_agent? @jackgerrits

**Review by ekzhu — APPROVED** [review]
Thanks. This is useful. As a next step we can put the exit reason in the chat result object returned by `initiate_chat` as well.

**Comment by ekzhu** [comment]
Pls resolve the conflicts.

**Comment by gagb** [comment]
closing because of inactivity.

**Pull request closed without merging**
