### PR TITLE
Correct small typos in system messages

### PR DESCRIPTION
**Pull request by pbadeer**
## Why are these changes needed?

Just correcting misspelling of the word "coordinator" in a number of default system messages.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by pbadeer** [comment]
@microsoft-github-policy-service agree

**Review by jackgerrits — APPROVED** [review]

**Review by victordibia — APPROVED** [review]
These look good to me. Thanks. 

@pbadeer , thanks for the updates.
In the future, for autogenstudio updates, it would be great to follow the autogenstudio [contribution guide ](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/README.md#contribution-guide) 

The main change is that autogenstudio is being heavily developed on the `autogenstudio` branch. It would be helpful to merge into that branch to ensure consistency. 

@jackgerrits @BeibinLi

**Comment by pbadeer** [comment]
Will use that branch next time, sorry for the mistake.

**Comment by sonichi** [comment]
Could you fix the code format error? You can use pre-commit to help.

**Pull request merged**
