### PR TITLE
AgentChat streaming API

### LINKED ISSUE #3969: Streaming messages from a run
### What feature would you like to be added?

Would be a simple way to integrate with UIs to show progress while executing a task, without getting into logging. 
```python
team = Swarm([agent1, agent2])
stream = await team.run_stream("What is bob's birthday?", termination_condition=MaxMessageTermination(3))
async for message in stream:
    print(message)
```

### Why is this needed?

Logging is too complicated for a quick start. Stream iterator is much more user friendly.

### PR DESCRIPTION
**Pull request by ekzhu**
Resolves #3969

Would be a simple way to integrate with UIs to show progress while executing a task, without getting into logging. 

```python
from autogen_ext.models import OpenAIChatCompletionClient
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.teams import Swarm
from autogen_agentchat.task import MaxMessageTermination

model_client = OpenAIChatCompletionClient(model="gpt-4o")

agent1 = AssistantAgent(
    "Alice",
    model_client=model_client,
    handoffs=["Bob"],
    system_message="You are Alice and you only answer questions about yourself.",
)
agent2 = AssistantAgent(
    "Bob", model_client=model_client, system_message="You are Bob and your birthday is on 1st January."
)

team = Swarm([agent1, agent2])

stream = team.run_stream("What is bob's birthday?", termination_condition=MaxMessageTermination(3))
async for message in stream:
    print(message)
```

```
source='user' content="What is bob's birthday?"
source='Alice' content=[FunctionCall(id='call_OMp2KGOi0HJNoJ1CP4sARKNq', arguments='{}', name='transfer_to_bob')]
source='Alice' content=[FunctionExecutionResult(content='Transferred to Bob, adopting the role of Bob immediately.', call_id='call_OMp2KGOi0HJNoJ1CP4sARKNq')]
source='Alice' target='Bob' content='Transferred to Bob, adopting the role of Bob immediately.'
source='Bob' content='My birthday is on 1st January.'
TaskResult(messages=[TextMessage(source='user', content="What is bob's birthday?"), ToolCallMessage(source='Alice', content=[FunctionCall(id='call_OMp2KGOi0HJNoJ1CP4sARKNq', arguments='{}', name='transfer_to_bob')]), ToolCallResultMessage(source='Alice', content=[FunctionExecutionResult(content='Transferred to Bob, adopting the role of Bob immediately.', call_id='call_OMp2KGOi0HJNoJ1CP4sARKNq')]), HandoffMessage(source='Alice', target='Bob', content='Transferred to Bob, adopting the role of Bob immediately.'), TextMessage(source='Bob', content='My birthday is on 1st January.')])
```

### CODE REVIEW

**Comment by gagb** [comment]
Why is there an error in the execution result of Alice?

**Comment by ekzhu** [comment]
> Why is there an error in the execution result of Alice?

This is a separate bug with auto generated handoff functions.

**Review by husseinmozannar — APPROVED** [review]
Looks great! Tested a few times, I'm not sure how I feel about the last message being TaskResult while everything else is consistent as message with source & content fields. Maybe if there is a way to have stream.messages and stream.task_result possibly? this is not necessary and just an optional thing completely

**Review by victordibia — APPROVED** [review]

**Comment by ekzhu** [comment]
> Looks great! Tested a few times, I'm not sure how I feel about the last message being TaskResult while everything else is consistent as message with source & content fields. Maybe if there is a way to have stream.messages and stream.task_result possibly? this is not necessary and just an optional thing completely 

Python current doesn't support returning from async generator. A hack is to return value through exception. https://discuss.python.org/t/allow-return-statements-with-values-in-asynchronous-generators/66886/2

**Pull request merged**
