### PR TITLE
[Blocking Issue] Add tests dependencies for qdrant and fix chromadb errors

### LINKED ISSUE #444: chromadb hardcoded path doesn't work in rag_chat in in kaggle kernal environment
https://github.com/microsoft/autogen/blob/50ac5476377c1b41330589a6cfc5c4e65b93079f/autogen/retrieve_utils.py#L353

image

Can we somehow set this path for chromadb dynamically. Tried using changing the path in client path in below code in retrieve_config but that doesn't seems to be reflecting.

` retrieve_config={
        "task": "code",
        "docs_path": "Somelink",
        "chunk_token_size": 1000,
        "model": config_list[0]["model"],
        "client": chromadb.PersistentClient(path="/tmp/chromadb"),
        "collection_name": "groupchat",
        "get_or_create": True,
    },
` 

@sonichi @qingyun-wu @thinkall 

Also this commit doesn't seems to work which was merged 2 days back

Fix tmp dir not exists https://github.com/microsoft/autogen/pull/401

### PR DESCRIPTION
**Pull request by thinkall**
## Why are these changes needed?

Add test dependencies for qdrant, a fix to #303 . Will trigger the tests for qdrant in the build and openai workflow.

Also fix an error caused by chromadb 0.4.15, there is class renaming in it. This will block all the other PRs.

Also fix a bug of creating collection while client is not given.

## Related issue number

Closes #444 

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by rickyloynd-microsoft — APPROVED** [review]
Nice and simple. Thanks for the quick build fix.

**Comment by thinkall** [comment]
https://github.com/microsoft/autogen/actions/runs/6648408017/job/18068423391?pr=435#step:9:245

@sonichi @qingyun-wu could you help check this test_math error? Thanks.

**Review by pcdeadeasy — APPROVED** [review]
LGTM

**Review by Owaiskhan9654 — APPROVED** [review]
Please Approve this.

**Review by gagb — APPROVED** [review]

**Pull request merged**
