### PR TITLE
Fix missing messages in Gemini history

### PR DESCRIPTION
**Pull request by luxzoli**
## Why are these changes needed?

Message is missing from history with Gemini.
Supplying safety settings in Vertex AI format, when VertexAI is used.

## Related issue number

Closes  [#2900](https://github.com/microsoft/autogen/issues/2900)

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by yiranwu0** [comment]
Can you add a test for this function?

**Comment by luxzoli** [comment]
Sure, I will add a test case as well for the function then

**Comment by luxzoli** [comment]
@yiranwu0 I have added the test case

P.S: the GitGuardian message is not from my changes, but from commits synchronized from the main branch of the original repo

**Comment by yiranwu0** [comment]
I think the message part is good. I don't know why the vertexai safety is needed here thought

**Comment by luxzoli** [comment]
> I think the message part is good. I don't know why the vertexai safety is needed here thought

The safety setting is not related to the bug with the message history. I have noticed that the VertexAI Gemini client expects safety settings in a slightly different way than the Genai client:
```
File "/home/lux_zoltan_andras/.local/lib/python3.10/site-packages/vertexai/generative_models/_generative_models.py", line 312, in _prepare_request
    raise TypeError(
TypeError: When passing a list with SafetySettings objects, every item in a list must be a SafetySetting object.
```
@yiranwu0 please let me know if I should remove the safety setting related part from this PR

**Comment by yiranwu0** [comment]
> > I think the message part is good. I don't know why the vertexai safety is needed here thought
> 
> The safety setting is not related to the bug with the message history. I have noticed that the VertexAI Gemini client expects safety settings in a slightly different way than the Genai client:
> 
> ```
> File "/home/lux_zoltan_andras/.local/lib/python3.10/site-packages/vertexai/generative_models/_generative_models.py", line 312, in _prepare_request
>     raise TypeError(
> TypeError: When passing a list with SafetySettings objects, every item in a list must be a SafetySetting object.
> ```
> 
> @yiranwu0 please let me know if I should remove the safety setting related part from this PR

Yeah it would be good if this PR only updates the messages and we can get it merged quickly. You can make another PR for the vertexai's safety setting

**Comment by luxzoli** [comment]
@yiranwu0 I have removed the safety settings related part from the PR.
I will create a separate PR for these changes then  🙂

**Comment by BeibinLi** [comment]
@yiranwu0  Do you have any other comments about this PR? 
@luxzoli  Can you create a jupyter notebook under the "notebook" folder using Vertex AI? Just want to show users how to use this feature.

**Review by yiranwu0 — APPROVED** [review]
LGTM!

**Comment by yiranwu0** [comment]
@luxzoli Just want to confirm, do you test locally by actually running it? In line 197, the input type changes from string to dict, does gemini allow it?

**Comment by luxzoli** [comment]
> @luxzoli Just want to confirm, do you test locally by actually running it? In line 197, the input type changes from string to dict, does gemini allow it?

@yiranwu0 yes, I have testen the changes multiple times and they work fine :)

**Review by yiranwu0 — APPROVED** [review]

**Comment by luxzoli** [comment]
> @yiranwu0 Do you have any other comments about this PR? @luxzoli Can you create a jupyter notebook under the "notebook" folder using Vertex AI? Just want to show users how to use this feature.

@BeibinLi sure, I will do it 🙂

**Pull request merged**
