### PR TITLE
Adding a notebook demostrating video transcript translate with whisper in AutoGen

### PR DESCRIPTION
**Pull request by chengxuan233**
## Why are these changes needed?
This is a Notebook using Whisper and GPT-3.5-turbo with AssistantAgent and UserProxyAgent to recognize and translate the speech sound from a video file and add the timestamp like a subtitle file. 
This is part of a project from the course DS 440 at Penn State University.

## Checks

- [✓] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by chengxuan233** [comment]
@microsoft-github-policy-service agree [company="{Penn State University}"]

**Comment by BeibinLi** [comment]
Fantastic! I just took a quick look at the notebook. Two minor suggestions
1. Can we combine the two notebooks together? For instance, we can have two sections within the same notebook.
2. Can we use an online video instead of a local file, so that other users can try it without changing anything.

**Comment by chengxuan233** [comment]
@microsoft-github-policy-service agree [company="{company="{your company}"] I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
@microsoft-github-policy-service agree

**Comment by chengxuan233** [comment]
@microsoft-github-policy-service agree

**Pull request merged**
