### PR TITLE
Use latest APIs for tool use, code execution and cache in topic pages

### PR DESCRIPTION
**Pull request by ekzhu**
## Why are these changes needed?

Use the latest APIs for the followings in topic pages:
1. Tool use
2. Caching
3. Code executors

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by ekzhu** [comment]
@qingyun-wu could you run the notebooks to make sure the outputs are expected? Much appreciated!

**Comment by qingyun-wu** [comment]
> @qingyun-wu could you run the notebooks to make sure the outputs are expected? Much appreciated!

Will do.

**Comment by qingyun-wu** [comment]
The reflection notebook's output is expected. "Approach 1. Two-agent chat with function call for task decomposition"of task_decomposition is not: The response of the tool call is null.
Screenshot 2024-03-18 at 10 53 43 PM

Haven't run the rest.

**Comment by ekzhu** [comment]
> The reflection notebook's output is expected. "Approach 1. Two-agent chat with function call for task decomposition"of task_decomposition is not: The response of the tool call is null. 
> 
> Haven't run the rest.

Looks like there is a bug in the notebook. The llm_config for planner and assistant agents should be separate. I am fixing it now.

**Comment by ekzhu** [comment]
@qingyun-wu @jackgerrits @sonichi Can you take a look? I have fixed the notebooks to use the latest APIs.

**Review by sonichi — APPROVED** [review]

**Pull request merged**
