### PR TITLE
Let run tests directly via `python test_xyz.py`, fix for `conftest` import via `sys.path.append`

### LINKED ISSUE #1120: [Bug]:  [Low Priority] Cannot run tests from a test's local folder. `conftest` is not found.
### Describe the bug

Prior to #1110, it was possible to run the tests from a test's local directory. E.g.

```sh
cd autogen/test/agentchat/contrib
python test_compressible_agent.py
```
or 
```sh
cd autogen/test/agentchat/contrib
pytest test_compressible_agent.py
```

But now, doing so raises the error: 
```
ModuleNotFoundError: No module named 'conftest'
```

Now, tests need to be run from the test root folder:
```sh
cd autogen/test
pytest agentchat/contrib/test_compressible_agent.py
```

This isn't a real problem, but it is a change in prior behavior, and it took me a minute to understand what was going on despite considerable prior experience with the tests.

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### Screenshots and logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by maxim-saplin**
I have added `sys.path.append()`  before all `from conftest import skip_openai` and also checked the test can be run directly.

## Related issue number

Closes #1120 and #1137

## Checks

- [N/A] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [N/A] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by rickyloynd-microsoft — APPROVED** [review]
Awesome!

**Review by afourney — APPROVED** [review]
I think this is generally fine.

I think it's worth considering in the future how we maybe restructure the tests directory to maybe ameliorate this, and the need to add both the parent and grandparent paths. 

Adding so many non-standard system paths feels a little suboptimal.

**Comment by maxim-saplin** [comment]
> I think this is generally fine.
> 
> I think it's worth considering in the future how we maybe restructure the tests directory to maybe ameliorate this, and the need to add both the parent and grandparent paths.
> 
> Adding so many non-standard system paths feels a little suboptimal.

Totally agree and I don't like the smell of the PR :)

IMO it is better to drop the requirement to have the tests runnable by theirselves and revert to tooling (such as PyTest or IDE) - this will also allow to avoid adding __main__ part at the bottom of files

**Comment by rickyloynd-microsoft** [comment]
> to avoid adding **main** part at the bottom of files

For me, the **main** part is a convenient way of selecting just the functions I want to run manually, without having to be in the IDE, or having to run pytest.

**Comment by afourney** [comment]
@rickyloynd-microsoft Yes, it's a pain (and not always ideal possible) to run every test in the file when trying to iterate on, or develop one specific test for a new PR or something. Obviously we want to run ALL tests before committing, but it's not necessary when trying to step through or debug one particular one.

**Pull request merged**
