### PR TITLE
Add Cerebras Integration

### PR DESCRIPTION
**Pull request by henrytwo**
## Why are these changes needed?

Add integration for Cerebras, which provides super low-latency, high speed LLM inference. Currently Llama 3.1-8B/70B are supported.

Tool calling examples have been provided in this PR, which also function with streaming. Additionally, token cost calculations have been implemented.

This PR mirrors the changes from: https://github.com/autogen-ai/autogen/pull/48

## Checks

- [X] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by henrytwo** [comment]
cc: @jackgerrits @afourney

**Review by ekzhu — APPROVED** [review]

**Comment by henrytwo** [comment]
Anyone know why these files that I didn't touch are failing the linter? https://github.com/microsoft/autogen/actions/runs/11111974198/job/30874062565?pr=3585#step:6:193

The first few seem legit, but I didn't touch any HTML stuff

**Review by afourney — APPROVED** [review]
The changes look great, and consistent with how other client providers are implemented. I do not have means to test the changes end-to-end, but what I see looks good. I believe there is some small format fixed that are needed to pass the test, but on substance this looks good.

**Review by gagb — APPROVED** [review]

**Comment by jackgerrits** [comment]
Ah the HTML thing is a line ending issue in main I am pretty sure, I'll open a PR for it

**Comment by henrytwo** [comment]
> Ah the HTML thing is a line ending issue in main I am pretty sure, I'll open a PR for it

Is there something I can do to fix it locally? It's actually breaking my git right now 😢

**Comment by jackgerrits** [comment]
> > Ah the HTML thing is a line ending issue in main I am pretty sure, I'll open a PR for it
> 
> Is there something I can do to fix it locally? It's actually breaking my git right now 😢

Yeah I had the same thing happen to me... I'm not sure. I'll have what I think is the fix merged in a few mins

**Comment by jackgerrits** [comment]
Cool, looks like the HTML file issue is gone, just some other formatting issues to be resolved then we can merge this

**Comment by henrytwo** [comment]
@jackgerrits can you approve the workflow please? I ran `pre-commit` locally to format the files

**Pull request merged**
