### PR TITLE
Fix example for LLM configuration docs

### PR DESCRIPTION
**Pull request by jackgerrits**
## Why are these changes needed?

The current simplest example does not work as the OpenAI client complains that "model" is not defined in the request.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by AaronWard — APPROVED** [review]
LGTM 👍

**Review by ekzhu — APPROVED** [review]
Great catch!

**Comment by ekzhu** [comment]
There is another issue perhaps related to this PR. When I run the following command outside of the project repo direcotry:

```
>>> import autogen
>>> config_list = autogen.get_config_list(["test"], api_type = "openai")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'autogen' has no attribute 'get_config_list'
``` 

It is complaining about the import issue. Could be related to #1526

**Comment by sonichi** [comment]
> There is another issue perhaps related to this PR. When I run the following command outside of the project repo direcotry:
> 
> ```
> >>> import autogen
> >>> config_list = autogen.get_config_list(["test"], api_type = "openai")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'autogen' has no attribute 'get_config_list'
> ```
> 
> It is complaining about the import issue. Could be related to #1526

This can happen when you have an "autogen" directory in the current path. If you import it from other places it works.

**Pull request merged**
