### PR TITLE
Add Language Agent Tree Search (LATS) notebook

### PR DESCRIPTION
**Pull request by andyz245**
## Why are these changes needed?

Uploading the notebook for LATS

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by andyz245** [comment]
@microsoft-github-policy-service agree

**Comment by andyz245** [comment]
@skzhang1 

Could you please review this pull request? Thank you!

**Comment by skzhang1** [comment]
Please formate the code: https://microsoft.github.io/autogen/docs/contributor-guide/pre-commit/

**Comment by andyz245** [comment]
made another one with the precommit check, thanks! @skzhang1

**Pull request closed without merging**
