### PR TITLE
add __init__.py for capabilities

### PR DESCRIPTION
**Pull request by btcioner**
## Why are these changes needed?

some error info like below:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-7afc2e96e5f4>](https://localhost:8080/#) in <cell line: 3>()
      1 import autogen
      2 from autogen import UserProxyAgent, config_list_from_json
----> 3 from autogen.agentchat.contrib.capabilities.teachability import Teachability
      4 from flaml import tune
      5 

ModuleNotFoundError: No module named 'autogen.agentchat.contrib.capabilities'

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by rickyloynd-microsoft** [comment]
Looks reasonable to me. @sonichi it appears that `agentchat/contrib/__init__.py` is empty. Is this intentional?

**Review by rickyloynd-microsoft — APPROVED** [review]
I've verified that the contrib/capabilities folder is missing from the pyautogen==0.2.4 package, and adding the folder manually under site-packages after a pip install fixes the problem. I assume that adding an __init__.py file per this PR will cause the package build process to pick up the capabilities folder. I also verified that the contents of __init__.py supplied by this PR allow Teachability and AgentCapability to be imported and run, although an empty __init__.py also seems to work.

**Comment by rickyloynd-microsoft** [comment]
I'll try to fix this pre-commit-check error.

**Comment by sonichi** [comment]
Could you please fix the code formatting error? You can use pre-commit.

**Comment by rickyloynd-microsoft** [comment]
> @btcioner The pre-commit-check fails because black wants the list to be on a single line like this:
> 
> `__all__ = ["Teachability", "AgentCapability"]`
> 
> Can you make this change in your fork? Thanks.

Oh, it looks like I've got access to your fork. I went ahead and made the change.

**Pull request merged**
