### PR TITLE
Magentic one example

### PR DESCRIPTION
**Pull request by husseinmozannar**
## Why are these changes needed?

Magentic-One has no example script showcasing how to create the agent team to solve tasks.

I create an example.py script to showcase magentic-one.

I also edited the orchestrator to return a final answer and not just the ledger.

I added minor comments to various magentic-one components to improve readability.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by husseinmozannar** [comment]
I'm still new to uv, not sure why uv.lock changed. 

@afourney  @gagb  I added a simple example script for magentic-one, let's keep brainstorming about the API for magentic-one and migration to agent-chat

**Comment by husseinmozannar** [comment]
I think it will be valuable to create a frontend interface that visualizes the agent graph + ledger + chat, to create demos for magentic-one release - keeping this PR a draft while I work on that

**Review by afourney — APPROVED** [review]
Looks good.

**Comment by rysweet** [comment]
@husseinmozannar - is this still meant to be in draft?

**Comment by husseinmozannar** [comment]
@ry

> @husseinmozannar - is this still meant to be in draft?

Just added a readme for the examples.

Feel free to merge now, instead of the interface, we will start with a log viewer. Thank you.

**Pull request merged**
