### PR TITLE
bump version to 0.2.9

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

Fixing test errors that block all the PRs.
Simplify contrib tests to reduce the latency.

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by afourney — COMMENTED** [review]
LGTM

**Review by pbadeer — APPROVED** [review]
LGTM

**Review by BeibinLi — APPROVED** [review]
LGTM. 

Why do the notebooks have the newline formatting now? Just curious.

**Comment by afourney** [comment]
> Why do the notebooks have the newline formatting now? Just curious.

No idea. `nbqa-black` is showing some instability. See #1418

**Pull request merged**
