### PR TITLE
WebSurfer changes - incl move to lazy init.

### PR DESCRIPTION
**Pull request by afourney**
## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by husseinmozannar — COMMENTED** [review]
why remove the arguments from init (_lazy_init), there are many scenarios where you launch the browser outside of websurfer and pass it as argument (e.g., webby)

**Comment by afourney** [comment]
> why remove the arguments from init (_lazy_init), there are many scenarios where you launch the browser outside of websurfer and pass it as argument (e.g., webby)

The parameters are added to the constructor. If we want to instantiate it outside and pass a reference, we should do that in the constructor too (in which case things are easier and we don't need lazy init at all)

Lazy init exists because the playwright code is async, and cannot be called from the constructor.... so we wait to do it on the first message

**Comment by husseinmozannar** [comment]
Now I get it, working on top of this PR for my changes, thanks

**Review by husseinmozannar — APPROVED** [review]
looks good

**Pull request merged**
