### PR TITLE
Correctly validating new real-world OpenAI API Key format, relaxing negative tests

### PR DESCRIPTION
**Pull request by nstielau**
## Why are these changes needed?

Using a real-world OpenAI API key, which successfully works with the OpenAI hosted models, I encountered a warning message that the API key was not valid.  This red-herring lead to slow debugging, as the issue was in fact a space character in an agent name rather than anything to do with the API key.  

# Approach

I've removed two negative tests.  Writing a validation implementation that passes these tests is possible, but in my opinion it is preferable to have a simple validation function that doesn't cover all possibilities.  It seems like 99.9% of the time, a user would copy/paste their API Key, and the updated function should catch common positive and negative tests.

Additionally, in my opinion, false positives that log the warning message incorrectly are as bad as false negatives which would not indicate the API Key when it is not working. 

# Reviewers

@wrfly and @AaronWard PTAL TY!

## Related issue number

n/a
See https://github.com/microsoft/autogen/pull/3078 for last changes

## Checks

- [X] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [X] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by nstielau** [comment]
@microsoft-github-policy-service agree

**Comment by AcePeed** [comment]
This PR would normally fix this issue #3345. I'm facing the same problem and can't wait for this PR to be merged 👍 .

**Comment by nstielau** [comment]
Thanks for connecting to that issue @AcePeed.

**Comment by AaronWard** [comment]
@sonichi Can you assign me as a reviewer?

**Comment by rseymour** [comment]
Also facing same issue a valid API key format is out of the hands of this library and OpenAI returns an error when one is valid.

**Comment by buddycat** [comment]
The updated regex still rejects my valid OpenAI api_key. It would need to be adjusted to allow for multiple underscores, possibly like ^sk-(?!.*--)([a-zA-Z0-9]+(?:-[a-zA-Z0-9_]+)*)$

**Comment by nstielau** [comment]
@buddycat can you give a test-case assertion for your key?

**Comment by buddycat** [comment]
Here's a test-case that should be true:

sk-proj-111111111122222aaaaaaaa_7777hhhhh_111111111122222aaaaaaa_99900000fggfffhgg

**Comment by jackgerrits** [comment]
Superseded by #3569

**Pull request closed without merging**
