### PR TITLE
Add Zep ecosystem doc and notebook

### PR DESCRIPTION
**Pull request by danielchalef**
## Why are these changes needed?

Added: Ecosystem markdown and Jupyter notebook demonstrating how to build Autogen agents with Zep's memory layer.

## Checks

- [X] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by danielchalef** [comment]
@microsoft-github-policy-service agree company="Zep Software, Inc."

**Comment by rysweet** [comment]
Hi @danielchalef - with the new release of autogen 0.4 we are going to be shortly coming up with a policy to provide clarity on the best way to create, discover, and share 3rd party integrations with AutoGen. Stay Tuned

**Comment by rysweet** [comment]
This PR is against AutoGen 0.2. AutoGen 0.2 has been moved to the 0.2 branch. Please rebase your PR on the 0.2 branch or update it to work with the new AutoGen 0.4 that is now in main.

**Comment by danielchalef** [comment]
@rysweet Rebased on 0.2. Base branch for PR switched to 0.2.

**Comment by danielchalef** [comment]
@jackgerrits @rysweet fixed formatting and spelling. pre-commit tests now pass.

**Comment by rysweet** [comment]
Thanks @danielchalef!

@jackgerrits I'm not sure where this one falls wrt the proposed policy updates.

**Comment by danielchalef** [comment]
> We should take the 0.2 one, and then for 0.4 would you check this and consider following the discovery guidance? https://microsoft.github.io/autogen/dev/user-guide/extensions-user-guide/index.html#creating-your-own-community-extension @danielchalef

Yeah - will be happy to do so.

**Comment by jackgerrits** [comment]
Just realized why the CI is failing for this one @danielchalef. The notebook needs to be edited so that is displayed on the website (just adding some metadata). See here: https://github.com/microsoft/autogen/blob/0.2/notebook/contributing.md

Once that is done the link checker should be happy

**Comment by danielchalef** [comment]
@jackgerrits Oops. I missed that. Fixed. Thx!

**Review by rysweet — APPROVED** [review]
thanks!

**Comment by danielchalef** [comment]
@rysweet thanks!

**Pull request merged**
