### PR TITLE
Add **kwargs to gpt_assistant_agent

### PR DESCRIPTION
**Pull request by iandjx**
## Why are these changes needed?
To further the customization of GPT Assisants as a Conversable agent, it is recommended to add `**kwargs` as part of the construction arguments that gets passed to `super().__init__()`

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by iandjx** [comment]
@microsoft-github-policy-service agree company="Magic"

**Comment by rickyloynd-microsoft** [comment]
@gagb fyi

**Comment by gagb** [comment]
@iandjx @rickyloynd-microsoft this will be addressed in https://github.com/microsoft/autogen/pull/665/files

**Comment by iandjx** [comment]
closed in favor of https://github.com/microsoft/autogen/pull/665/files

**Pull request closed without merging**
