### PR TITLE
add EcoAssistant blog

### PR DESCRIPTION
**Pull request by JieyuZ2**
## Why are these changes needed?

Add a blog introducing EcoAssistant

## Related issue number

N/A

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by JieyuZ2** [comment]
@microsoft-github-policy-service agree

**Comment by sonichi** [comment]
Both code formatting check and doc checks fail.

**Comment by sonichi** [comment]
you can use `pre-commit` to help with the formatting.

**Comment by JieyuZ2** [comment]
> you can use `pre-commit` to help with the formatting.

yes. all checks are passed now

**Review by skzhang1 — APPROVED** [review]

**Pull request merged**
