### PR TITLE
feat(autogenstudio): Anthropic Support

### PR DESCRIPTION
**Pull request by JGalego**
## Why are these changes needed?

This PR adds support for Anthropic models via [Anthropic API](https://www.anthropic.com/api) or [Amazon Bedrock](https://aws.amazon.com/bedrock/claude) (relies on https://github.com/microsoft/autogen/pull/3103).

**Demo:** [Travel Agent workflow with Claude 3 Haiku via Amazon Bedrock 🧳🗺️⁀જ✈🏝️🍹🌞🌊](https://youtu.be/SSpkJzkExek)

image

## Related issue number

N/A

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by JGalego** [comment]
@microsoft-github-policy-service agree

**Review by makkzone — COMMENTED** [review]
@JGalego Did you test this with workflow session under playground?

**Comment by JGalego** [comment]
> @JGalego Did you test this with workflow session under playground?

Tested with the Travel Agent workflow 🧳🗺️ Full recording available [here](https://youtu.be/SSpkJzkExek).

autogenstudio_anthropic

**Review by makkzone — APPROVED** [review]
Looks good to me.

**Review by makkzone — COMMENTED** [review]
@marklysze @sonichi Can you please add your reviews too?

**Comment by JGalego** [comment]
> @JGalego any chance you can base this PR on the autogenstudio branch following the guide here? https://microsoft.github.io/autogen/docs/autogen-studio/getting-started#contribution-guide

Sure, opened a new one based on `autogenstudio` >  https://github.com/microsoft/autogen/pull/3350. Just need some time for testing before it's ready for review.

**Comment by JGalego** [comment]
Superseded by https://github.com/microsoft/autogen/pull/3350

**Pull request closed without merging**
