### PR TITLE
headsup about dependency change

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

headsup about dependency change

## Related issue number

#203

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by olaoluwasalami — APPROVED** [review]

**Review by shauryr — APPROVED** [review]
lgtm

**Review by rickyloynd-microsoft — APPROVED** [review]

**Review by yogeshhk — APPROVED** [review]
lgtm

**Comment by 05hiteshbansal** [comment]
lgtm

**Review by 05hiteshbansal — APPROVED** [review]

**Review by Steellgold — APPROVED** [review]

**Review by mrauter1 — CHANGES_REQUESTED** [review]
Line 113 of README.md should be updated for consistency:
*OLD* ... It offers a drop-in replacement of `openai.Completion` or `openai.ChatCompletion` adding powerful functionalities... *OLD*
*NEW*
Autogen also helps maximize the utility out of the expensive LLMs such as ChatGPT and GPT-4. It offers enhanced LLM inference with powerful functionalites like tuning, caching, error handling, templating. For example, you can optimize generations by LLM with your own tuning data, success metrics and budgets.
*NEW*

**Review by manish7017 — APPROVED** [review]
lgtm

**Review by mrauter1 — APPROVED** [review]
Looks good to me

**Review by LeoLjl — APPROVED** [review]
lgtm

**Review by pcdeadeasy — APPROVED** [review]
Looks Goid.

**Review by HyperCodec — APPROVED** [review]

**Comment by masterujjval** [comment]
looks great to me!

**Pull request merged**
